### ISSUE TITLE
Fix writing to alternate screen functionality on Windows Enterprise

### ISSUE THREAD

**Issue by dr4ds** [crossterm-rs/crossterm#128]
Example: https://github.com/TimonPost/crossterm/blob/master/examples/alternate_screen.rs doesn't write to alternate screen but to main screen.

**Comment by TimonPost** [comment]
I can't reproduce this on Windows or Linux, which operating system are you on?

**Comment by dr4ds** [comment]
win 10 ltsb, with cmd

**Comment by TimonPost** [comment]
I am still not seeing any problems, which version are you using and which command do you run to test the example?

**Comment by dr4ds** [comment]
I check it on win 10 pro and it works i guess it only doesn't work on enterprise edition of windows.

**Comment by TimonPost** [comment]
That's so strange, I'm wondering what the reason could be.

**Comment by longwusha** [comment]
I am using enterprise edition of windows and I will give it a try.

**Comment by longwusha** [comment]
I got the same result. Both cmd and powershell do not work correctly.

**Comment by longwusha** [comment]
Nothing is printed on the screen during the loop printing process. When the cycle is over (after 5 seconds), the final result is printed.

**Comment by MrYurihi** [comment]
This happens to me even without windows enterprise, just regular windows 10

**Comment by TimonPost** [comment]
And you have windows ... ?

**Comment by MrYurihi** [comment]
it works on Powershell, but not cmd (or git bash for that matter)

**Comment by MrYurihi** [comment]
Just noticed something while looking through, but shouldn't this if block be reversed?
https://github.com/TimonPost/crossterm/blob/216105aa06bbc5790203b309bd8293fecc91075c/crossterm_screen/src/screen/alternate.rs#L42-L48

**Comment by MrYurihi** [comment]
Switching that actually fixed the bug for me

**Comment by TimonPost** [comment]
You are right, that should definitely be switched.

**Comment by svartalf** [comment]
#153 should fix the issue found by @MrYurihi

**Comment by TimonPost** [comment]
Needs to be validated and when proved that fixed the problem this can be closed.

**Comment by imdaveho** [comment]
Btw, while this should be closed if you verified the fix; there should be some consideration to provide a `write` using WinAPI for those cases when `if supports_ansi() == false`, otherwise using `std::io::stdout()` and `println!` only prints to the main buffer.

I can confirm this by changing cmd.exe to use legacy mode (no ansi support) and running the example for alternate_screen.
