### ISSUE TITLE
Fix error when using `command::new()` and `read_sync()` on windows 7

### ISSUE THREAD

**Issue by sigmaSd** [crossterm-rs/crossterm#145]
Hi, here's a weird(also read as annoying) bug I'm running into:
```rust
use crossterm::Crossterm;
fn main() {
    let crossterm = Crossterm::new();
    let mut stdin = crossterm.input().read_sync();
    loop {
        if let Some(key_event) = stdin.next() {
            // any command run here will fail
            std::process::Command::new("ipconfig").spawn();
        }
    }
```
Spawning the command fails with this error `The application was unable to start correctly (0xc0000142)`
This happens on windows 7, works fine on linux.

**Comment by prabirshrestha** [comment]
I had same error code but in different project. https://github.com/wez/wezterm/issues/27#issuecomment-493857904

**Comment by TimonPost** [comment]
I will try to see what causes did, I don't have any idea yet.

**Comment by TimonPost** [comment]
I can confirm this problem for Windows 7, strange enough when running the application in administrator mode it will work. It might be a permission thing.

**Comment by sigmaSd** [comment]
I tried with administrator mode and it still didn't work.

**Comment by TimonPost** [comment]
This might be solved, reading has had some improvement here: #101, needs to be verified.

**Comment by sigmaSd** [comment]
Already tested, unfortenatly issue remains

**Comment by sigmaSd** [comment]
Hi, tested again with `crossterm = "0.17.5"`, this is no longer an issue, program works as expected.
