### ISSUE TITLE
Make crossterm support terminal resize events

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#165]
# Task Description
When the terminal resizes, fire an event on the input reader (`Sync/Async reader`). 

# Task Todo

- [ ] Implement windows 
- https://docs.microsoft.com/en-us/windows/console/input-record-str#members
 - https://github.com/TimonPost/crossterm/blob/master/crossterm_input/src/input/windows_input.rs#L176
- [ ] Implement Unix
- https://github.com/osa1/tiny/blob/master/term_input/src/lib.rs#L80
- https://github.com/osa1/tiny/blob/master/term_input/src/lib.rs#L212

Windows is quite easy to integrate the input event, this is implemented already over [here](https://github.com/TimonPost/crossterm/blob/inputex/crossterm_input/src/input/windows_input.rs#L280). 

Although Linux is a bit more difficult, the Linux system reads ANSI codes from the stdout (tty). Those ANSI codes are [interpreted ](https://github.com/TimonPost/crossterm/blob/inputex/crossterm_input/src/input/input.rs#L155) into key events. 

we need to figure out 
1) how to get the terminal to resize event, I saw some solutions using the Signal Crate, I somewhere had that in my local branches. But that requires us to add a dependentie.
2) how to implement that into the current design. Because the input event does not come from the tty but from the terminal resize event thrower.

**Comment by zrzka** [comment]
This issue contains old description, it contains old tasks, ... There's `Event::Resize` in the `input_rewrite` branch which will be merged very soon.
