### ISSUE TITLE
crossterm v0.10.1 can't open raw mode when input is piped to stdin

### ISSUE THREAD

**Issue by timothyb89** [crossterm-rs/crossterm#188]
In previous versions of crossterm (v0.8.2) it was possible to enable raw input mode when input was piped in, e.g.

```
echo "hello world" | my-crossterm-app
```

Using some trickery, you could continuously read piped output while still receiving key events. However, in crossterm v0.10 (and probably since the big v0.9 refactor, but I haven't confirmed), `RawScreen::into_raw_mode()` returns an error if input is piped into the app:

```
Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }
```

I've made a small demo of this working in v0.8 but breaking in v0.10: https://github.com/timothyb89/crossterm-stdin-test

**Comment by andersk** [comment]
Surely `into_raw_mode` should be conceptually an operation on stdin, not stdout? Then you could call it on any fd that you think is a terminal, whether it happens to be fd 0 or not. In addition to that problem, some applications may want to set input to raw mode even if they aren’t using crossterm at all for output.

The docs have an [explanation](https://docs.rs/crossterm/0.10.2/crossterm/trait.IntoRawMode.html#why-is-this-type-defined-on-writers-and-not-readers) of why it wasn’t written that way, but the explanation is manifestly wrong—the underlying [code](https://github.com/TimonPost/crossterm/blob/master/crossterm_utils/src/sys/unix.rs#L41), at least on Unix, calls operations on fd 0 (stdin), not fd 1 (stdout).

**Comment by TimonPost** [comment]
Sorry I have never responded to this issue. Since basically, the whole crossterm library was refactored after 0.10 and we have been moving over to /dev/tty for everything this issue might be resolved. I'll close it for now.

**Comment by timothyb89** [comment]
Thanks for the update! I'll give it a try and report back if there's still trouble.
