### ISSUE TITLE
Find a way how to fix re-enable failing tests

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#219]
#216 enabled testing of everything on the Travis CI, but some tests were marked with the `#[ignore]` attribute to make it passing. You can still run them locally with:

* Windows - `cargo test --all -- --ignored`
* macOS/Linux - `cargo test --all --exclude crossterm_winapi -- --ignored`

**NOTE:** Following tests are failing on the Travis CI, but some of them are failing even locally (macOS). Mentioning it, because I do not want to say that the Travis CI is the only bad guy here.

**`crossterm_terminal/src/terminal/test.rs - winapi_tests::resize_winapi`**

* Failing with `31 != 30`
* [Travis job](https://travis-ci.org/zrzka/crossterm/jobs/584997489#L184-L186)

Normally, I'd say that this is a Travis problem. But when I saw `31 != 30`, it seems like an off-by-one error. Can anyone with Windows machine check this? I've got macOS & Linux around only.

```rust
#[cfg(windows)]
mod winapi_tests {
    use super::super::*;

    // TODO - Test is ignored, because it returns wrong result (31 != 30)
    #[test]
    #[ignore]
    fn resize_winapi() {
        let terminal = WinApiTerminal::new();

        terminal.set_size(30, 30).unwrap();

        let (x, y) = terminal.terminal_size();

        assert_eq!(x, 30);
        assert_eq!(y, 30);
    }
}
```

**`crossterm_cursor/src/cursor/test.rs - reset_safe_ansi`**
**`crossterm_cursor/src/cursor/test.rs - goto_ansi`**

* Failing with _The build has been terminated_
* [Travis job](https://travis-ci.org/TimonPost/crossterm/jobs/585148492#L276-L281)

Both tests are stalled on the Travis CI, which leads to a killed job after +- 10 minutes.

**`crossterm_terminal/src/terminal/test.rs - resize_ansi`**

* Failing with `80 != 50`
* [Travis job](https://travis-ci.org/TimonPost/crossterm/jobs/585149217#L302-L306)

**`crossterm_winapi/src/console_mode.rs - test::set_get_mode`**

* Failing with _Getting mode failed_
* [Travis job](https://travis-ci.org/TimonPost/crossterm/jobs/585148493#L174-L183)

**`crossterm_terminal/src/terminal/terminal.rs - terminal::terminal::Terminal::exit`**

* Failing with _Test executable failed (exit code 256)_
* [Travis job](https://travis-ci.org/TimonPost/crossterm/jobs/585149218#L247-L259)

This one is a docstring example marked with `no_run` for now.

**Comment by TimonPost** [comment]
> Normally, I'd say that this is a Travis problem. But when I saw 31 != 30, it seems like an off-by-one error. Can anyone with Windows machine check this? I've got macOS & Linux around only.

I am on windows and will validate those tests for you. The problem is probably introduced in the latest release where we changed from 0-based to 1-based.

**Comment by zrzka** [comment]
Fixed, tests that can be enabled are enabled.
