### ISSUE TITLE
Publicly available sys modules

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#247]
Some sub-crates have a `sys` module, which is public. And these `sys` modules are used inside other crates sometimes. For example, `crossterm_terminal` crate does use `crossterm_cursor::sys::winapi::Cursor`.

Shouldn't all `sys` modules be considered as an implementation detail and the public interface should be used instead of them? Like `use crossterm_cursor::TerminalCursor` in this case?

**Comment by TimonPost** [comment]
I belive that the terminal is the only one using another crate. I would like to remove that. Although that brings in one problem, when clearing with ANSI codes, the cursor will reset to 0,0 or beginning of the line. But when clearing with WinAPI, we have to manually change the cursor position to 0,0. To sync this behaviour we do need to have that dependency, unfortunately. An idea that we could do is duplicating the winapi cursor moving logic. It might not be the best choice although it isn't that much code and we can remove the whole dependency.

**Comment by TimonPost** [comment]
crossterm_input has a reference to crossterm_screen as well because it requires raw modes

**Comment by TimonPost** [comment]
Fixed in https://github.com/crossterm-rs/crossterm-cursor/pull/2
