### ISSUE TITLE
Sync raw mode behavior

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#250]
The terminal `raw mode` does not function the same on UNIX and Windows. I tried to find resources to figure out which flags to turn on or turn of. However, it is is not the same yet. 

- Here we [enable ](https://github.com/TimonPost/crossterm/blob/master/crossterm_screen/src/sys/winapi.rs#L35)raw modes.
- Here we [disable](https://github.com/TimonPost/crossterm/blob/master/crossterm_screen/src/sys/winapi.rs#L46) raw modes 
- Those are the [flags ](https://github.com/TimonPost/crossterm/blob/master/crossterm_screen/src/sys/winapi.rs#L21)crossterm uses 

# Task
- [ ] Figure out which flags are needed to simulate [UNIX raw mode behavior](https://github.com/TimonPost/crossterm/blob/master/crossterm_utils/src/sys/unix.rs#L46)

# Related

- https://github.com/TimonPost/crossterm/issues/214

**Comment by 3kyro** [comment]
Checking the windows console documentation I believe the following can approximate UNIX "raw" screen.

Based on [High-Level Console Modes](https://docs.microsoft.com/en-us/windows/console/high-level-console-modes), for an application to be in "raw" mode the following input and output modes need to be disabled:

#### Input Modes

- Line input mode
- Processed input mode
- Echo input mode 

#### Output Modes

- Processed output mode
- Wrapping at EOL output mode

However both the output modes are not applicable for a POSIX like RawScreen.
Processed output mode is: 

> Used with a console screen buffer handle to cause the system to perform the appropriate action for ANSI control characters that are written to a screen buffer. 

and so applicable only for AlternateScreen.

Wrapping at EOL output mode i:

> Used with a console screen buffer handle to cause the current output position (cursor position) to move to the first column in the next row (line) when the end of the current row is reached.

Also applicable for an alternate screen; furthermore, this behavior is not present in  POSIX "raw" and alternate screen.

For this changes, the `ConsoleMode` default `handle` needs to be changed to a `HandleType::InputHandle` and the `RawModeCommand` `mask` needs to be changed to `ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT | ENABLE_PROCESSED_INPUT`

Tested on Windows 10 Powershell and also appears to solve #214

**Comment by TimonPost** [comment]
Thanks for the research. I will look into this as well and see if it compares to unix functionality

**Comment by 3kyro** [comment]
Thanks for looking into it. From my side I have tested in windows 10 Powershell and cmd and the terminal behaves similarly to a Gnome terminal on ubuntu 19.04 and a Ubuntu wls terminal on windows 10.

**Comment by TimonPost** [comment]
Great, so one thing I don't understand is why can we just change Output Handle to Input Handle?

**Comment by 3kyro** [comment]
That is a good question.

Maybe relevant: SyncReader::next() seems to behave differently on windows eg:

```
fn main() {

    let input = input();

    let mut stdin = input.read_sync(); 

    loop {
        if let Some(_) = stdin.next() {
        }    
    }    
}
```
does not print any characters on a windows terminal although RawScreen is not set. In a linux terminal, input characters are echoed as expected (and InputEvents are all sent together after \n)

**Comment by 3kyro** [comment]
Cursor position is reported differently between windows and Linux. In windows, cursor position is given from the start of the screen buffer, while for Linux its given in relation to current window. For example,  in windows console (PowerShell an cmd) `cursor.pos().1` will increment as the terminal scrolls down, while in gnome terminal it stays constant.

Interestingly, in the integrated terminal of vscode, this is not the case, and cursor position follows the linux behavior.

Sorry for the spam, but I guess I collect all these small differences here even-though they might not relate to RawScreen. If this is not ok, I can create a new issue.
