### ISSUE TITLE
Windows cursor is unsound: impl From<HANDLE> for Cursor

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#252]
Originally reported by @MaulingMonkey:

https://github.com/crossterm-rs/crossterm-cursor/blob/13f6c0878ac871750c5893689e4743ac8084c13b/src/sys/winapi.rs#L129-L135

This allows 100% "safe" rust code to store - and later use from safe fns - possibly invalid `HANDLE`s, which is a soundness issue.  There's potentially a similar issue with `impl From<crossterm_winapi::Handle> for Cursor` if that fails to enforce a "handle is valid" as a precondition/invariant (winapi's HANDLE definitely doesn't)

**Comment by TimonPost** [comment]
I am not sure if I follow what is meant by this issue.
