### ISSUE TITLE
Crossterm Style API-discussion

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#254]
In this issue, we will discuss all the API changes we want to make for crossterm_style.

**Comment by TimonPost** [comment]
@zrzka: "For Object Style I had the following toughts"

If yes, then I've got something like this on my mind ...

```rust
#[derive(Debug, Clone, Default)]
pub struct ObjectStyle {
    fg_color: Option<Color>,
    bg_color: Option<Color>,
    attrs: Vec<Attribute>,
}

impl ObjectStyle {
    pub fn apply<D: Display + Clone>(&self, val: D) -> StyledObject<D> {
        StyledObject {
            object_style: self.clone(),
            content: val,
        }
    }

    pub fn new() -> ObjectStyle {
        ObjectStyle::default()
    }

    pub fn background(mut self, color: Color) -> ObjectStyle {
        self.bg_color = Some(color);
        self
    }

    pub fn foreground(mut self, color: Color) -> ObjectStyle {
        self.fg_color = Some(color);
        self
    }

    pub fn attribute(mut self, attr: Attribute) -> ObjectStyle {
        self.attrs.push(attr);
        self
    }
}
```

In other words ...

* I'd make fields private
* I'd rename `apply_to` to `apply`
* I'd remove `set_`, ... and use just `foreground`, `background`, ...
* I'd change `add_attr` to `attribute` which should return self as other methods

... it will lead to something like ...

```rust
let style = ObjectStyle::new()
    .foreground(Color::Blue)
    .background(Color::Yellow)
    .attribute(Attribute::Italic);

let foo = style.apply("bar");
let bar = style.apply("baz");
```

But all of these changes are breaking and not sure if we should make them. What's the goal of this PR? Same what I did with the `-cursor`? If yes, then be aware that I did internal refactoring without any breaking change (except the private `sys` module), polished documentation and that's all. If the answer is no, then it's fine to include them.

**Comment by TimonPost** [comment]
`ObjectStyle` is most often not used directly by users. So the changes we make on this type are not affecting many people. 

It is very common for a builder pattern to have no `set` so I have no problem removing at all. As well after working some time with rust I see more value in having full names as well. So great idea!

**Comment by TimonPost** [comment]
I have 3 proposals as well:

1. Rename `StyledObject` to `StyledContent`
2. Rename `ObjectStyle` to `ContentStyle`

My motivation behind this is that `StyledObject` wraps `Display`able content. And this is not really an 'Object'. So by renaming this to 'StyledContent'  it is more clear what it is, styled content. The same principle goes for `ObjectStyle` -> `ContentStyle`

3. `StyledObject` contains public private fields as well. We should probably make those private as well.

```rust
pub struct StyledObject<D: Display + Clone> {
    object_style: ObjectStyle,
    content: D,
}
```
Then add the following functions (if change 1,2 as well are approved. Otherwise replace `content_style` with `object_style`).

```rust 
fn content() -> D;
fn content_style() -> ObjectStyle
```

**Comment by zrzka** [comment]
Trait names - `Styler` vs `Colorize` -> `Styles` & `Colorizer` || `Style` & `Colorize`.

**Comment by TimonPost** [comment]
Styler & Colorizer although I have one problem with this, Colorizer is not a word in the dictionary and thus I decided to use Colorize a couple of months ago.

**Comment by zrzka** [comment]
`Attribute::NoInverse` should be renamed to `Attribute::NoReverse`.

**Comment by TimonPost** [comment]
Going to be closed in favor of #286, more API discussion can be done there.

**Comment by TimonPost** [comment]
Actual tasks are moved over here #286

**Comment by TimonPost** [comment]
Closing, because ideas were merged.
