### ISSUE TITLE
KeyEvent::Tab not sent on windows

### ISSUE THREAD

**Issue by 3kyro** [crossterm-rs/crossterm#260]
on window_input.rs, the check for `KeyEvent::Tab` is nested inside a `key_state.has_state(SHIFT_PRESSED)` check and is not correctly sent .

> ```
>                 } else if key_state.has_state(SHIFT_PRESSED) {
>                     // Shift + key press, essentially the same as single key press
>                     // Separating to be explicit about the Shift press.
>                     if character == '\t' {
>                         Some(KeyEvent::BackTab)
>                     } else {
>                         Some(KeyEvent::Tab)
>                     }
> ```

Since there is a refactoring in progress for `crossterm-input` I leave it to be corrected there.

**Comment by TimonPost** [comment]
Thanks, I can fix this in my PR for input

**Comment by TimonPost** [comment]
Fixed https://github.com/crossterm-rs/crossterm-input/pull/3
