### ISSUE TITLE
crossterm-style Command for SetBg bug?

### ISSUE THREAD

**Issue by MaulingMonkey** [crossterm-rs/crossterm#261]
https://github.com/crossterm-rs/crossterm-style/blob/541f9e36ed267c64fadc366e5cf8bd2e4ae2832c/src/color.rs#L117

I believe this should call set_**b**g, not set_**f**g

**Comment by TimonPost** [comment]
Thanks, yes this is a big mistake. I will open a PR for that directly.

**Comment by TimonPost** [comment]
Is going to be fixed in https://github.com/crossterm-rs/crossterm-style/pull/2
