### ISSUE TITLE
Synchronize mouse button events coordinates with the cursor

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#267]
I find it a bit weird that the cursor does use `0, 0` for the first column/row, but the mouse events do use `1, 1` for the first column/row. I'd assume that everything starts from `0, 0`.

Not much investigation done on my side, I just noticed this when working on the documentation/examples.

**Comment by TimonPost** [comment]
Agree, that should be the same.

**Comment by zrzka** [comment]
@TimonPost did you have a chance to validate this issue on Windows as well? Before touching it, I'd like to be sure that this isn't just some macOS/UNIX quirk or even just my computer only.

**Comment by zrzka** [comment]
All three types with coordinates are producing numbers starting at 1.

<img width="1217" alt="Screen_Shot_2019-10-03_at_11_34_18" src="https://user-images.githubusercontent.com/1084172/66115828-e423fc80-e5d1-11e9-8504-21ab30bce20b.png">

My test code:

```rust
use crossterm_input::{InputEvent, KeyEvent, MouseEvent, RawScreen, Result, TerminalInput};

fn main() -> Result<()> {
    let input = TerminalInput::new();
    let _raw = RawScreen::into_raw_mode()?;

    let mut reader = input.read_sync();
    input.enable_mouse_mode()?;

    loop {
        if let Some(event) = reader.next() {
            match event {
                InputEvent::Keyboard(KeyEvent::Esc) => break,
                InputEvent::Mouse(mouse) => {
                    match mouse {
                        MouseEvent::Press(_, x, y) => println!("Press: {}x{}", x, y),
                        MouseEvent::Hold(x, y) => println!("Move: {}x{}", x, y),
                        MouseEvent::Release(x, y) => println!("Release: {}x{}", x, y),
                        _ => {}
                    };
                }
                _ => {}
            };
        }
    }

    input.disable_mouse_mode()?;
    Ok(())
}
```

**Comment by TimonPost** [comment]
![image](https://user-images.githubusercontent.com/19969910/66124905-f14ae680-e5e5-11e9-8235-08a3f9a80c4a.png)

In the windows terminal, they start with 1,1 as well

**Comment by zrzka** [comment]
Thanks, will PR it later today ...
