### ISSUE TITLE
Crossterm Command API-discussion

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#268]
In this issue, we will discuss all the API changes we want to make for all the sort of `Commands` crossterm provides.

**Comment by TimonPost** [comment]
Rename:
- Show -> ShowCursor
- Hide -> HideCursor 
- UP -> CursorUp
- Down -> CursorDown
- Left -> CursorLeft
- Right -> CursorRight

**Comment by TimonPost** [comment]
Add:

- [X] ResetColor
- [ ] EnterAlternateScreen/LeaveAlternateScreen 

Mark the ones that are done

**Comment by Canop** [comment]
Up, Down, Left and Right should be changed too, yes.

**Comment by Canop** [comment]
It's a minor semantics point but IMO the output is *where* you send all commands, while `Print` is the command. It's also more consistent with `PrintStyledFont` (whose name might be not ideal too, as it's a styledObject as I understand it, not a font).

**Comment by zrzka** [comment]
I'd go even further ...

* Goto -> MoveCursorTo
* Up -> MoveCursorUp
* Down -> MoveCursorDown
* Left -> MoveCursorLeft
* Right -> MoveCursorRight
* SavePos -> SaveCursorPosition
* ResetPos -> RestoreCursorPosition
* Hide -> HideCursor
* Show -> ShowCursor
* BlinkOn -> EnableCursorBlink
* BlinkOff -> DisableCursorBlink

Why?

* I personally don't care much about the length, we have autocompletion everywhere, I care about clarity.
* I'd like to see `Cursor` in these commands, `Screen` in others, etc. We have multiple crates (for now, modules in the future) and it must be clear what the command is doing.
* It's also kind of synced with methods like `TerminalCursor::move_up`, etc.

**Comment by TimonPost** [comment]
Mmm, I like the clarity for those names. But When we talk about pos, for example, is there any pos we can safe other than the cursor position? Like with Hide/Show there was the argument that it could be hidden/show terminal/cursor. I personally think we should keep this short and clear to understand.

**Comment by TimonPost** [comment]
- SetBg -> SetBgColor/SetBackgroundColor?
- SetFg -> SetFgColor/SetForegroundColor?
- Clear -> ClearScreen?

**Comment by Canop** [comment]
SetBg and SetFg seem OK for me. And Clear takes an argument which prevents ambiguity.

**Comment by zrzka** [comment]
IMHO we should be consistent. If there will be `SaveCursorPosition` then we should have `SetForegroundColor`, etc. IOW we should pick one style for naming methods, commands, traits, ... and use it everywhere. Abbreviation allowed here, not allowed there, ... leads to an unclear interface for the users.

**Comment by zrzka** [comment]
`execute` & `queue` macros require to bring `std::io::Write` into the scope. Can we somehow do it in the macro itself, so user isn't forced to do it? No investigation yet, came to my mind couple of times.

**Comment by TimonPost** [comment]
Most of the things have been implemented or worked on. Closing this issue now.
