### ISSUE TITLE
Win32 raw mode not working

### ISSUE THREAD

**Issue by coffeenotfound** [crossterm-rs/crossterm#272]
I have problems getting into raw mode on Windows as `RawScreen::into_raw_mode()` always returns an error.
Strangely enough, the returned error is `IoError(Os { code: 0, kind: Other, message: "Der Vorgang wurde erfolgreich beendet." })` ("The operation was executed successfully")

**Comment by TimonPost** [comment]
Maybe this will be fixed with #250, going to validate the PR for that issue today

**Comment by coffeenotfound** [comment]
Oh didn't notice this was already being worked on.

I will close this issue for now
