### ISSUE TITLE
crossterm_style's ResetColor is not re-exported in lib.rs

### ISSUE THREAD

**Issue by Zooce** [crossterm-rs/crossterm#273]
If I use crossterm as my only dependency, I don't get access to ResetColor from crossterm_style because it isn't re-exported like the others:

```rust
#[cfg(feature = "style")]
pub use crossterm_style::{
    color, style, Attribute, Color, Colored, Colorize, ObjectStyle, PrintStyledFont, SetAttr,
    SetBg, SetFg, StyledObject, Styler, TerminalColor,
};
```

**Comment by TimonPost** [comment]
Good catch. It will be fixed soon. Sorry for the inconvenience. Try to use `TerminalColor::reset()` for temporary solution.

**Comment by Zooce** [comment]
The workaround I'm using is actually similar, `Color::Reset`.

**Comment by zrzka** [comment]
One thing to note here - the `ResetColor` is in the `master` branch only and not released yet.
