### ISSUE TITLE
Determine the terminal size in a subshell (unix)

### ISSUE THREAD

**Issue by Canop** [crossterm-rs/crossterm#276]
Like all other libraries I've checked, crossterm fails to read the terminal size when the crossterm based program is ran in a subshell.

I've found a solution which works in my tests: call `tput cols` and `tput lines` and parse the result:
```
fn tput_value(arg: &str) -> Option<u16> {
    match process::Command::new("tput").arg(arg).output() {
        Ok(process::Output{stdout, ..}) => {
                let value = stdout.iter()
                    .map(|&b| b as u16)
                    .take_while(|&b| b>=48 && b<=58)
                    .fold(0, |v, b| v*10 + (b-48));
                if value > 0 { Some(value) } else { None }
        }
        _ => None,
    }
}

pub fn terminal_size() -> (u16, u16) {
    let mut size = Terminal::new().size();
    #[cfg(unix)]
    {
        if size.is_err() {
            if let (Some(w), Some(h)) = (tput_value("cols"), tput_value("lines")) {
                return (w, h);
            }
        }
    }
    ...
```

I'm willing to post a PR.

Check-list before the PR:
- [ ] wait for the various crossterm-rs subcrate to be merged
- [ ] try to find if there's a similar problem (and solution) on Windows
- [ ] decide a name and return type for this function (which should probably be consciously called as it starts new processes)

(In the meantime I've included the function in termimad which will let me run more tests)

**Comment by zrzka** [comment]
I know that the `tput` is with us for a long time. As a safety measure, are we aware of any UNIX like platform (`#[cfg(unix)]`), which doesn't have `tput`?

This approach is pragmatic and I'm fine with it. Although, do we know how the `tput` works? I mean, is there're an easy way how to achieve the same thing without `process::Command::new("tput")`?

**Comment by joshtriplett** [comment]
Invoking a separate program has *many* problems, not least of which that it won't work if the program runs in a container or chroot.

`tput` typically invokes the `TIOCGWINSZ` ioctl, which returns the terminal size.

**Comment by Canop** [comment]
@joshtriplett I agree that invoking a separate program is problematic (maybe use it in a separate function) but you can easily check in a subshell that this solution works while the TIOCGWINSZ ioctl doesn't (and doesn't work either in a container).

**Comment by TimonPost** [comment]
This issue is fixed with #283, if not, re-open.

**Comment by joshtriplett** [comment]
> you can easily check in a subshell that this solution works while the TIOCGWINSZ ioctl currently doesn't

What do you mean by "in a subshell" here? I have checked that running tput in a subshell still correctly figures out the terminal size. tput just tries stderr, stdout, and stdin, to see if they're hooked up to the terminal, and if not then it opens `/dev/tty` and uses that. What is tput doing that crossterm couldn't do itself, and under what circumstances does TIOCGWINSZ not work in a subshell?

**Comment by Canop** [comment]
@joshtriplett Write a `sub_program` program needing to know the size of the terminal. Let's imagine it writes that size on stdout.

Then call it as

    echo "my program says $(sub_program)"

Then `sub_program` runs in a subshell and the previous way of obtaining the terminal dimension didn't work.

What tput does could probably be reproduced, and I'm all for doing it, but in the meantime calling it is a working workaround.
