### ISSUE TITLE
NoBold (21) attribute doesn't work reliably over terminals

### ISSUE THREAD

**Issue by vmedea** [crossterm-rs/crossterm#294]
- In tmux, it seems to do nothing, it doesn't disable bold
- In tilix and gnome-terminal (both based on vte) it enables underline (???)
- in alacritty it works

It's more or less expected that not all attributes work on all terminals, however I'm not sure how to handle this. For example, [cursive](https://github.com/gyscos/cursive/blob/master/src/backend/crossterm.rs#L260) currently assumes the end-attributes all work, or at least do nothing unexpected. Using the bold attribute at all fills the screen with bold and/or underlined text.

Edit: Gah, looks like some terminals use 22 instead: https://github.com/curl/curl/issues/2736 . But that disables italic as well as bold.

**Comment by TimonPost** [comment]
Terminal attributes are a pain, and are interpreted differently. I'm not sure if we can do anything about this. And leave the responsibility over to the user wether to use an attribute for his terminal.

**Comment by vmedea** [comment]
Yeah, it's especially a pain for disable attributes. It's not that bad if say, a request to italicize text is ignored, but if the attribute works but it can never be canceled it becomes a mess from there on.

**Comment by TimonPost** [comment]
There are attributes to reset the attributes. Attribute::Reset for example

**Comment by vmedea** [comment]
Yes, what I've always did myself when writing terminal code is to use `0;` before all attribute settings instead of bothering to keep track of incremental bits. But Cursive doesn't do this, however, at the moment. I'm ideally trying to find a backend for Cursive that works widely over terminals but is not ncurses :smile:

**Comment by TimonPost** [comment]
Maybe you shouldn't use special attributes then. And just stay with the most basics. I'm not sure if anything can be done with this. Unless we keep track of the terminal type and different ways it supports attributes but that is going to be a nasty job.

**Comment by TimonPost** [comment]
Maybe we can move this issue to cursive. And let it fix this attribute problem. I am not sure if attribute interpretation by a terminal is not a problem of crossterm or terimon. They just do what Wikipedia tells to do. However, if you think otherwise I am open to ideas!

**Comment by vmedea** [comment]
Sure, I honestly have no clue here. Pushing the responsibility to the user of the library is fine but it means *they* need some means to determine what they can use, naive use of this library results in code that isn't compatible with common terminals.

I'll stick with ncurses for now. at least it handles bold without problems. I liked that termion and crossterm support true color, but thinking of it, that's not as big a deal as the rabbit hole of cross terminal compatibility.

**Comment by aeosynth** [comment]
this inconsistency should at least be noted in the docs to warn people away from using it
