### ISSUE TITLE
Leaving alternate screen doesn't change the terminal mode to cooked

### ISSUE THREAD

**Issue by PonasKovas** [crossterm-rs/crossterm#303]
If I enter an alternate screen like this:
```rust
let altscreen_handle = AlternateScreen::to_alternate(true).unwrap();
```
It enables raw mode in the terminal.
However, when the handle goes out of scope, or when `AlternateScreen::to_main(&self)` is called, raw mode is not being disabled.

**Comment by TimonPost** [comment]
That is strange. Which operating system are you on?

**Comment by TimonPost** [comment]
When I do:

```rust
use crossterm::screen::AlternateScreen;
use std::time::Duration;
use std::thread;

fn main () {
    let alternate_screen = AlternateScreen::to_alternate(true).unwrap();

    thread::sleep(Duration::from_millis(2000));

    drop(alternate_screen);
}
```

Everything works perfectly fine. 

Note that raw mode is disabled when `RawScreen` drops, which is embodied in `AlternateScreen`.

**Comment by TimonPost** [comment]
It will be closed. This API does not exist, and therefore, if the issue still remains, another issue can be created.
