### ISSUE TITLE
Some keys interpreted as space, others not registered

### ISSUE THREAD

**Issue by Necroforger** [crossterm-rs/crossterm#310]
When pressing `caps lock`, `scroll lock`, `num lock`, and `pause/break`, crossterm interprets it as the space key.

I'm using Windows 10 command prompt and powershell with crossterm set to use raw mode on the alternate screen.

I've also run into issues with not being able to match for certain `Ctrl` and `Alt` combinations. 
for example:
`alt+hjkl`

**Comment by TimonPost** [comment]
- ALT + MORE KEYS 
- CAPS/scroll/num lock 
- pauze/break

**Comment by TimonPost** [comment]
Going to close this issue. Those keys are not yet supported. In the future when the input module is finished we are going to think about adding more keys.
