### ISSUE TITLE
crossterm interfering with rustyline under Linux

### ISSUE THREAD

**Issue by dwuertz** [crossterm-rs/crossterm#311]
Since crossterm 0.12, rustyline behaves strangely inside my app under Linux (didn't test on Win). Example to reproduce issue:
```
extern crate crossterm;
extern crate rustyline;

fn main() {
    let mut input = crossterm::input::input().read_sync();
    let mut rl = rustyline::Editor::<()>::new();
    let readline = rl.readline("> ");
}
```
When e.g. pressing left/right arrow keys, rustyline::Editor apparently does random thinks like ignoring some key presses or inserting [D or [C sequences into the edit text line. After removing the read_sync() line, everything working fine again. No issue with crossterm <= 0.11

**Comment by TimonPost** [comment]
Are you using two input readers at the same time? This is not possible. I think that this has to do with the fact that crossterm is now spawning an input reading that reads input with MIO on UNIX systems. Therefore if rustyline reads input as well they will steal input bytes from each other and will cause both to have strange behavior.

**Comment by dwuertz** [comment]
Depends on what you mean by "at the same time". I use both in the same application (a file manager), yes. It's primarily a crossterm-based TUI, and for certain actions (like renaming a file) a present a text input using rustyline which temporarily takes control over all terminal I/O. I consider this a valid use case. Apparently, crossterms input event handling is not tied to some object lifetime, because if I only create a temporary TerminalInput which is imediatly dropped again, I still have the problem
```
extern crate crossterm;
extern crate rustyline;

fn main() {
    crossterm::input::input().read_sync();
    // Being ignorant about crossterm's implementation, I would assume that input handling is stopped
    // at this point because TerminalInput object has been dropped.
    let mut rl = rustyline::Editor::<()>::new();
    let readline = rl.readline("> ");
}
```

**Comment by dwuertz** [comment]
For the record, I figured out a work-around using the recently introduced `input::stop_reading_thread()`:
```
extern crate crossterm;
extern crate rustyline;

fn main() {
    let mut input = crossterm::input::input().read_sync();
    // crossterm's input used here

    // Destroys current reader thread, input object not usable anymore after that.
    crossterm::input::stop_reading_thread();

    let mut rl = rustyline::Editor::<()>::new();
    let readline = rl.readline("> ");

    // Spawns new reader thread
    input = crossterm::input::input().read_sync();
    // Continue with crossterm input handling
}
```
This is fine for me now but honestly feels a bit like a hack. I would prefer if I didn't have to kill the thread altogether but instead maybe just suspend/resume it.
Seeing that crossterm's input handling is currently being overhauled, I would appreciate if someone could come up with a nicer API.

**Comment by zrzka** [comment]
Yeah, sorry for this. The mentioned fn was added as a quick hack/fix just to allow users to stop the thread. It doesn't make much sense to fix it properly while the rewrite is progressing well.

Here's an example of how the new API will look like:

https://github.com/crossterm-rs/crossterm/blob/input_rewrite/examples/input_demo.rs

Just two fns - poll & read and you can use them for both sync/async. Everything else was removed (from the public API) with the background reading thread (UNIX).

**Comment by TimonPost** [comment]
Going to close this issue. Unfortunately, you have to live with the hack until the new version.
