### ISSUE TITLE
TerminalInput massively slows down std::process::Command

### ISSUE THREAD

**Issue by adam-mcdaniel** [crossterm-rs/crossterm#316]
**Describe the bug**
std::process::Command STDIN/STDOUT lags extremely after a TerminalInput object has been created at some point in the past.
**To Reproduce**
- Create a TerminalInput object in some function where it will be dropped before input.
- Make a std::process::Command call to `nano` or some other terminal text editor.
- Observe how SLOW the process runs

**Expected behavior**
I expected the process to behave regularly, and for STDIN/STDOUT to not lag
**OS**
 - Zorin OS (Ubuntu 18.04)

**Terminal/Shell**
- Bash

**Comment by TimonPost** [comment]
We removed `TerminalInput` and therefore this issue might be irrelevant. I will validate if this is still the case.
