### ISSUE TITLE
Remove all feature flags

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#317]
When I look at the feature list ...

```
default = ["cursor", "style", "terminal", "screen", "event"]
cursor = ["lazy_static", "event", "winapi/wincon", "winapi/winnt", "winapi/minwindef"]
style = ["lazy_static", "winapi/wincon"]
terminal = ["cursor"]
screen = ["lazy_static", "winapi/wincon", "winapi/minwindef"]
event = ["mio", "lazy_static", "parking_lot", "screen", "terminal", "winapi/winnt", "winapi/winuser", "winapi/wincon", "winapi/synchapi", "winapi/namedpipeapi", "winapi/impl-default"]
```

... it's getting complicated, feature A requires feature B, ...

I propose to remove all features and make them always available.

Cons?

* Slower compile time
  * Really? How many users do disable default features and enables only selected ones?
* Does not affect size, linker eliminates dead/not used code.

Or less radical change:

```
default = []
event = []
```

Just one feature named `event`. What are the use cases?

* User is either drawing, writing, changing colors, getting size, cursor position, ...
* User is doing the previous stuff + consuming events

In this way we will avoid downloading & compiling `mio`, `parking_lot`, ... if user does not want to consume events.

**Comment by TimonPost** [comment]
Agree, there are way more flags than we had before and it is getting unmanageable. I do like the idea to have the event feature flag, because it doesn't make much sense to download and compile mio/parking lot for a user that only uses crossterm for styling for example. If we can eliminate those two deps it seems like a good plan!

**Comment by zrzka** [comment]
As discussed in the Discord, all features will be enabled by default and all feature flags will be removed.

New feature flag `event-stream` will be introduced and this flag will make `EventStream` available (`futures::stream::Stream`). Why? When the `event-stream` is enabled:

* number of crates jumps from 35 to 60,
* compile time is 4x longer.

None of these things are acceptable for anyone who's not interested in `futures::stream::Stream`.
