### ISSUE TITLE
0.14 Release Soon?

### ISSUE THREAD

**Issue by zicklag** [crossterm-rs/crossterm#337]
No rush if you've got stuff you want to do before-hand, but I was curious if you have any idea when 0.14 is going to be released?

I'm working on a project and I could really use the screen resize events, plus the new events API looks awesome. I'd just use the git version, but I'm depending on another crate that isn't compatible with the master version, so I can't just put a `[replace]` in my `Cargo.toml`.

**Comment by TimonPost** [comment]
We will be releasing it soon. The even module had just a few things to be finetuned in order for it to go live. One was cancelation the other one was parsing performance and the return of false positives from poll. There are PR's for all of those:

- Merge #333 -> #326 -> #336 -> #332 -> #328 

If those are merged, we have to finish the [release documentation](https://github.com/crossterm-rs/crossterm/wiki/Upgrade-from-0.13-to-0.14). Then we can do the release. Trelease is going to come depending on how wast we merge the PR's.

**Comment by zicklag** [comment]
Thanks for the response. That sounds great. :)

I'm using [Termimad](https://github.com/Canop/termimad) for my [Lucky](https://github.com/katharostech/lucky) project's documentation pages. The resize events will allow me to recalculate the text wrapping when the terminal size changes.

**Comment by TimonPost** [comment]
Great! The author of that crate is our discord, and waiting on it as well. I guess there will ben a release of termiad as well soon after our release.

**Comment by TimonPost** [comment]
Released
