### ISSUE TITLE
Disabling raw mode does not work

### ISSUE THREAD

**Issue by adam-mcdaniel** [crossterm-rs/crossterm#341]
**Describe the bug**
Disabling raw mode does not work. This is pretty bad, considering that it completely disables programs using Crossterm to call other applications within the program. For example, its impossible to write a Shell using crossterm & raw mode without this feature working, the inherited STDIN and STDOUT of the program being executed are screwed up and cant be reset.

**To Reproduce**
Get input using the `input` object, and drop the `RawScreen`, which should disable raw mode again. Then, try to call another executable using the std::process::Command struct.

Heres an example.

```rust
use crossterm::{input::{input, InputEvent}, screen::RawScreen};

fn getch() -> Option<InputEvent> {
    let input = input();
    let raw = RawScreen::into_raw_mode();
    let mut sync_stdin = input.read_sync();
    let result = sync_stdin.next();

    result
}

fn main() {
    loop {
        for _ in 0..10 {
            println!("{:?}", getch());
        }

        std::process::Command::new("python").spawn();
    }
}
```

**Expected behavior**
What SHOULD happen in the example snippet is that the raw mode should be disabled, and the `python` interpreter should run as expected like when called in the terminal. This is not what happens.

Here's an example in termion that acts as intended;
```rust
extern crate termion;

use std::io::{stdin, stdout, Write};
use termion::event::Key;
use termion::input::TermRead;
use termion::raw::IntoRawMode;

fn main() {
    let stdin = stdin();
    let mut stdout = stdout().into_raw_mode().unwrap();

    write!(
        stdout,
        "{}{}q to exit. Type stuff, use alt, and so on.",
        termion::clear::All,
        termion::cursor::Goto(1, 1)
    )
    .unwrap();
    stdout.flush().unwrap();

    for c in stdin.keys() {
        write!(
            stdout,
            "{}{}",
            termion::cursor::Goto(1, 1),
            termion::clear::All
        )
        .unwrap();

        match c.unwrap() {
            Key::Char('q') => {
                stdout.suspend_raw_mode();
                std::process::Command::new("python").status();
                stdout.activate_raw_mode();
            }
            Key::Char(c) => println!("{}", c),
            Key::Alt(c) => println!("^{}", c),
            Key::Ctrl(c) => println!("*{}", c),
            Key::Esc => println!("ESC"),
            Key::Left => println!("←"),
            Key::Right => println!("→"),
            Key::Up => println!("↑"),
            Key::Down => println!("↓"),
            Key::Backspace => println!("×"),
            _ => {}
        }
        stdout.flush().unwrap();
    }

    write!(stdout, "{}", termion::cursor::Show).unwrap();
}
```
Before python is called, raw mode is disabled and the terminal acts as expected for Python. When raw mode is enabled again, the terminal can go back to retrieving input in raw mode.

**OS**
This fails on both Linux and Windows so far, it might fail on even more OSes.
Ive only tested Linux and Windows.

**Terminal/Shell**
PowerShell and Bash using the VSCode terminal emulator, the Hyper terminal emulator, and the XTerm terminal emulator

**Comment by TimonPost** [comment]
Thanks for the report. I can look into this later today. I have two things to say.

1. The examples are not quite the same. You enable/disable raw mode so many times after one and another in the crossterm example.  Can you try the following snipped.

```rust
fn getch() -> Option<InputEvent> {
    let input = input();
    let mut sync_stdin = input.read_sync();
    let result = sync_stdin.next();
    result
}

fn main() {
    loop {
         let raw = RawScreen::into_raw_mode();

        for _ in 0..10 {
            println!("{:?}", getch());
        }

       drop(raw);

        std::process::Command::new("python").spawn();
    }
}
```

2. The mast branch has quite some improvements with input reading and enabling raw modes. You might want to try that. I can rewrite your examples as well later today. Have a look over [here ](https://github.com/crossterm-rs/crossterm/wiki/Upgrade-from-0.13-to-0.14) for migration notes.

**Comment by adam-mcdaniel** [comment]
Using this example still doesnt work as intended. Explicitly dropping the RawScreen should effectively be the same as instantiating it in a function call.

Also using the master branch and replacing `RawScreen` with `enable_raw_mode` and `disable_raw_mode` yields the same results.

**Comment by TimonPost** [comment]
The whole input system is refactored, this issue can be closed.
