### ISSUE TITLE
Cant run interactive-test with steps provided

### ISSUE THREAD

**Issue by geoeo** [crossterm-rs/crossterm#345]
**Describe the bug**
Can not run interative-test example with steps provided

**To Reproduce**
1. cd to 'corss-term folder
2. run `cargo run --example examples/interactive-test`

**Expected behavior**
Example runs

**OS**
 - e.g. MacOs

**Terminal/Shell**
 - e.g. Mac Terminal

**Comment by geoeo** [comment]
The output is `error: no example target named `examples/interactive-test``

**Comment by TimonPost** [comment]
Cd into that folder and run cargo run. I will check why this isn't working.

**Comment by geoeo** [comment]
The workaround works. Thanks!

**Comment by TimonPost** [comment]
Can be closed, used above solution.
