### ISSUE TITLE
Readd AlternateScreenWriter

### ISSUE THREAD

**Issue by MOZGIII** [crossterm-rs/crossterm#352]
**Is your feature request related to a problem? Please describe.**
New command API is quite low level, it'd be great if `crossterm` provided an higher-level object.

**Describe the solution you'd like**
I'd like an `AlternateScreenWriter` to bound the screen configuration with the lifetime of the terminal.

```rust
struct AlternateScreenWriter<W: std::io::Writer>(W);
impl<W: std::io::Writer> std::io::Writer for AlternateScreenWriter<W> { ... }
impl<W: std::io::Writer> AlternateScreenWriter<W> {
    pub fn new(w: W) -> Result<Self, ErrorKind> {
        enable_raw_mode()?;
        execute!(&mut w, EnterAlternateScreen)?;
        Ok(Self(w))
    }
}
impl<W: std::io::Writer> Drop for AlternateScreenWriter<W> {
    fn drop(&mut self) {
        execute!(&mut self.0, LeaveAlternateScreen).unwrap();
        disable_raw_mode().unwrap();
    }
}
```

**Describe alternatives you've considered in any**
I just have this in my code currently.
Before I manually invoked `enable_raw_mode` and `execute!(..., EnterAlternateScreen)` and the corresponding reverse calls in the places where I create/drop `stdout`.

**Additional context**
It pretty much used to exist, but now it doesn't.

It's less than ideal, however it seems to be somewhat correct and does the job.

**Comment by zrzka** [comment]
Thanks for the request. It was removed on purpose with a goal to provide low level API only & one way to achieve the desired task. I'm not really sure we want something like this back, because it's going to violate "one way" rule. The low level API is here so you can build your own higher level stuff on top the low level one.

**Comment by MOZGIII** [comment]
Maybe we could an an `util` module? `futures` crate had the same issue and they solve it by moving everything non-essential to `futures-util` crate. Might work for this crate too.

**Comment by TimonPost** [comment]
I would be open to such a thing. We can create a separate crate with extensions on top of crossterm to make it work a bit easier. However, I do not have time for this yet. Feel free to make a start.

**Comment by TimonPost** [comment]
Closing this issue because we are not planning to implement this behavior. Either create your own wrapper or use the provided alternative crate.
