### ISSUE TITLE
Cargo Warning From `queue!` macro: use of deprecated item 'std::error::Error::description'

### ISSUE THREAD

**Issue by zicklag** [crossterm-rs/crossterm#356]
**Describe the bug**

When compiling my project I get a warning from cargo wherever the `queue!` macro is used:

    warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()

**To Reproduce**

Use the `queue!` macro in a project.

**Expected behavior**

There should be no warning

**OS**
 - Ubuntu 18.04

**Terminal/Shell**

- N/A

**Comment by TimonPost** [comment]
Fixed
