### ISSUE TITLE
unresolved import `crossterm::event::EventStream`: no `EventStream` in `event`

### ISSUE THREAD

**Issue by FilipLitwora** [crossterm-rs/crossterm#357]
Hi, I'm following [this example](https://github.com/crossterm-rs/crossterm/blob/master/examples/event-stream-async-std.rs), but this line  `use crossterm::{event::{DisableMouseCapture, EnableMouseCapture, Event, EventStream, KeyCode}};` gives following error : `unresolved import crossterm::event::EventStream: no EventStream in event`

my cargo.toml :
```
[package.metadata.docs.rs]
 all-features = true

 [dependencies]
 crossterm = "0.14.1"
 futures = {version = "0.3", optional = true}
futures-timer = "2"
async-std = "1"

[features]
event-stream = ["futures"]

```

**Comment by TimonPost** [comment]
You should enable the event-stream feature for crossterm.

 crossterm = { version = "0.14.1", features = ["event-stream"] }

**Comment by FilipLitwora** [comment]
> You should enable the event-stream feature for crossterm.
> 
> crossterm = { version = "0.14.1", features = ["event-stream"] }

Thanks!
