### ISSUE TITLE
process does not exit successfully on windows

### ISSUE THREAD

**Issue by 3kyro** [crossterm-rs/crossterm#358]
**Describe the bug**
When using sys::exit(), the process ends with an exit code of 256, producing the following error on windows terminals:

> error: process didn't exit successfully: `target\debug\crosstest.exe` (exit code: 256)

**To Reproduce**
1. Create a simple binary application with the following main.rs
``` Rust
fn main() {
    crossterm::terminal::exit();
}

```
2. Compile and run the application on a windows terminal (Powershell or cmd)
3. See error

**Expected behavior**
The process should exit successfully with exit code zero.

**OS**
 - Windows

**Terminal/Shell**
 -  CMD, Powershell

**Possible fix**
The exit code 256 is used on sys/windows.rs line 36
``` Rust
pub(crate) fn exit() {
    ::std::process::exit(256);
}
```
This is probably a misreading of std::process::exit() documentation example, where an exit code of 256 is given for demonstration reasons.

**Comment by TimonPost** [comment]
Your correct, when it was implemented I misunderstood the documentation. However, what should it be?

**Comment by 3kyro** [comment]
I guess it should just be 0 as on linux for a successful exit. 

On this note, does exit() only signify a successful exit? Should an exit code not be passed to std::process::exit?

**Comment by TimonPost** [comment]
Either we want to expose that code in the public API, or remove the whole function. I do consider to just remove it. It doesn't provide much value to crossterm. What do you think?

**Comment by 3kyro** [comment]
I agree with you, if it serves only as a wrapper to std::process::exit() then it should just be removed. A possible use of a terminal::exit() could be in returning the terminal in its original state before exiting (disabling raw mode, clearing attributes etc), the crate documentation is however clear that these modes are in the responsibility of the user to disable before exiting.

**Comment by TimonPost** [comment]
The exit function 'exists' for historical reasons, it used to reset the terminal back to the defaults. However, this is probably already 1 year not the case anymore.

**Comment by TimonPost** [comment]
Is removed in 0.16
