### ISSUE TITLE
Make use of /dev/tty for reading terminal size.

### ISSUE THREAD

**Issue by Lucretiel** [crossterm-rs/crossterm#362]
**Is your feature request related to a problem? Please describe.**
Currently, the terminal::size function is hardcoded (on unix) to read the terminal size from stdout. However, on some applications (like broot), stdout is redirected to something useful and the UI parts are rendered to the terminal on stderr.

**Describe the solution you'd like**
Either a separate set of _stderr methods should be added, or the exisiting ones should be modified to prefer stderr if it detects that stdout isn't a terminal.

Related to https://github.com/Canop/broot/issues/131

**Comment by TimonPost** [comment]
Good one, we have had a discussion about this. I do not have a good alternative implementation in mind yet. I would like to keep it a single method at least.

**Comment by Lucretiel** [comment]
I think a reasonable default would be:

```
if stdout.isatty() {
    stdout.size()
} else {
    stderr.size()
}
```

**Comment by TimonPost** [comment]
Can't we just use `/dev/tty`?

Like:

```rust
#[allow(identity_conversion)]
pub(crate) fn size() -> Result<(u16, u16)> {
    // http://rosettacode.org/wiki/Terminal_control/Dimensions#Library:_BSD_libc
    let mut size = winsize {
        ws_row: 0,
        ws_col: 0,
        ws_xpixel: 0,
        ws_ypixel: 0,
    };
    let fd = open("/dev/tty", O_RDWR); 
    if let Ok(true) =
        wrap_with_result(unsafe { ioctl(fd, TIOCGWINSZ.into(), &mut size) })
    {
        Ok((size.ws_col, size.ws_row))
    } else {
        tput_size().ok_or_else(|| std::io::Error::last_os_error().into())
    }
}
```

**Comment by Lucretiel** [comment]
That seems reasonable to me.

**Comment by TimonPost** [comment]
#381
