### ISSUE TITLE
Is raw mode disabled after panic?

### ISSUE THREAD

**Issue by krevativ** [crossterm-rs/crossterm#368]
**Describe the bug**
I often see a strange bahaviour after panic. If a panic occurs, it destroys the formatting in my terminal. After fixing the panic and starting again, the Clear command seems also to have no effect anymore. This is pretty annoying during development because I need to restart the session every time. So I just assume that the raw mode isn't disabled after panic. Or is it? If no, is there a way to do it myself?

```rust
use crossterm::{
    terminal::{disable_raw_mode, enable_raw_mode},
};

fn main() {
    enable_raw_mode();
    println!("Enter raw mode");
    panic!();
    disable_raw_mode();
}
```

**Expected behavior**
Raw mode should be disabled in case of a panic.

**OS**
 - MacOs

**Terminal/Shell**
 - iTerm2 + zsh

**Comment by TimonPost** [comment]
> So I just assume that the raw mode isn't disabled after panic. 
Indeed, raw mode is an terminal session setting. When panicing the terminal will still be in raw mode. 

A solution could be to try to hook into `panic!` and disable raw mode in that hook. 

https://doc.rust-lang.org/std/panic/fn.set_hook.html

**Comment by krevativ** [comment]
@TimonPost Great! It fixed the problem. Thanks for the quick reply.

**Comment by TimonPost** [comment]
Great to hear! Will close this issue.
