### ISSUE TITLE
Enabling/disabling the wrapping of text

### ISSUE THREAD

**Issue by tillarnold** [crossterm-rs/crossterm#370]
**Is your feature request related to a problem? Please describe.**
I'd like to use crossterm to output text on one line and if the output text is wider than the terminal the part of the text that dosn't fit is cut of. This is especially a problem if the text being printed is unicode text. Because then I cannot be sure how wide the text will be exactly and simply print that substring. (See the note on https://github.com/unicode-rs/unicode-width about how "The computed width values may not match the actual rendered column width")

**Describe the solution you'd like**
If possible I'd like to have a `Command` available for enabling/disabling the wrapping of text. So something on the lines of `EnableTextWrapping` & `DisableTextWrapping`.

**Additional context**
My brief research has led me to belive that this might be possible to implement using the `Esc[?7h` and `Esc[?7l` ANSI Escape sequences (http://ascii-table.com/ansi-escape-sequences-vt-100.php) on unix and the `SetConsoleMode` function with the `ENABLE_WRAP_AT_EOL_OUTPUT` (0x0002) bit in the `dwMode` on windows (https://docs.microsoft.com/en-us/windows/console/setconsolemode).

**Comment by powerconnector** [comment]
I think this can be closed as #485 has been merged?

**Comment by lilithium-hydride** [comment]
Yeah, this can definitely be closed.
https://docs.rs/crossterm/latest/crossterm/terminal/struct.DisableLineWrap.html

**Comment by TimonPost** [comment]
Awesome.
