### ISSUE TITLE
Control + J read as enter.

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#371]
**Describe the bug**
CTRL + J is read as enter. 

https://github.com/Canop/broot/issues/177

**Expected behavior**
I should receive CTRL + J when pressing enter

**OS**
 - e.g. MacOs, Linux

**Comment by sharnoff** [comment]
I encountered this issue as well - I'd love to work on it, if possible. Where should I look?

**Comment by TimonPost** [comment]
You should look at the event parsing code. This is in the event/sys/unix folder. I will put some links in here in a bit.

**Comment by TimonPost** [comment]
Fixed
