### ISSUE TITLE
[Support] Windows: Initial console color not set

### ISSUE THREAD

**Issue by Nukesor** [crossterm-rs/crossterm#374]
Hi there!

First of all, thanks for providing crossterm! It's super helpful.

I'm currently writing a commandline table formatting library, which aims to also provide colors and attributes for text styling. As you probably already guessed, I'm using crossterm's `Color` and `Attribute` to achieve this.

My code basically looks like this:
```
/// The representation of a single cell in a table row.
/// Each cell contains a string, which will later be displayed at the respective row/column.
pub struct Cell {
    pub(crate) content: String,
    pub(crate) fg: Option<Color>,
    pub(crate) bg: Option<Color>,
    pub(crate) attributes: Vec<Attribute>,
}

pub fn style_line(line: String, cell: &Cell) -> String {
    let mut content = style(line);

    // Apply text color
    if let Some(color) = cell.fg {
        content = content.with(color);
    }

    // Apply background color
    if let Some(color) = cell.bg {
        content = content.on(color);
    }

    // Apply background color
    for attribute in cell.attributes.iter() {
        content = content.attribute(*attribute);
    }
    content.to_string()
}
```
This is pretty straight-forward and only uses a quite small subset of crossterm's features.

**Here is what I want to do:**

I'm planning to allow users to create styled output, even if they **aren't** in an terminal environment.
This seems to work quite well in Unix environments, however my tests fail, if I'm trying to create styled output for windows in a non-terminal environment.

I'm getting this error:
```
##[error]thread 'styled_table' panicked at 'Initial console color not set', src\libcore\option.rs:1185:5
```

After looking through your code I found the `ORIGINAL_CONSOLE_COLOR` variable that should be initialized via `init_console_color`. I'm guessing that `init_console_color` is not run, since there doesn't seem to be an error from crossterm-winapi.

**My question is:**

What's the best course of action? Should I use other functions when formatting content for windows or is it simply not possible to create formatted output for windows in a non-terminal environment?

I'm not very familiar with windows-related coding and I'm quite new to low-level terminal stuff in general. This is why I thought it would be a good idea to ask first before spending hours digging through your code base.

I would be very glad, if you could help me with this problem. Thanks in advance!

Best regards,
Arne

**Comment by TimonPost** [comment]
The type `StyledContent` is what you are replicating with your code. You can use `PrintStyledContent` command to print some colored text. After this command, the colors will be reverted back to normal. Concerning the error, I am not sure why that is happening.

**Comment by Nukesor** [comment]
Well, I wanted to provide a unified interface for manipulating Cells. The Cell struct of course implements a few other fields/ methods. The example above is just a boiled down version of the original code. 

However, implenting this was super easy! Tried to do the same with termion and it was a real pain in the ass.

I'll try to debug the error, when I find some time. Until then I'll probably just drop Windows support :D

Feel free to close the issue. I'll reopen it, when I come back to the problem.

Thanks for your help!
