### ISSUE TITLE
Panic: Windows: "Original console mode not set"

### ISSUE THREAD

**Issue by xobs** [crossterm-rs/crossterm#377]
**Describe the bug**

When dropping the terminal object on Windows, the following error is produced:

```
thread '<unnamed>' panicked at 'Original console mode not set', src\libcore\option.rs:1190:5
```

**To Reproduce**

The following program produces this error on Windows:

```rust
extern crate terminal;

fn main() {
    terminal::stdout();
}
```

The following program does NOT panic on Windows:

```rust
extern crate terminal;

fn main() {
    terminal::stdout().act(terminal::Action::EnableMouseCapture);
}
```

**Expected behavior**
It shouldn't panic

**OS**
 - Windows

**Terminal/Shell**
 - Terminal Preview

**Version**
 - Crossterm: 0.14.2
 - Terminal: 0.2.0

**Comment by TimonPost** [comment]
Thanks for the issue! I think it is a bug thanks for reporting, I will have a look at this in 8 hours en publish a patch as soon as possible. I think it is related to `terminal` crate tough

**Comment by TimonPost** [comment]
The reason why this error occurs is that the `BackendImpl` for terminal will unset the mouse event monitoring. In crossterm this will restore the earlier statically saved terminal modes.  Though if you only create the instance and do not set the mouse event monitoring before the drop of `BackendImpl` this mode is not set and crossterm throws a panic. 

This is quite a crucial bug so however, I suggest you to call  `terminal::stdout().act(terminal::Action::EnableMouseCapture);` before the `Terminal` instance will be disposed.

**Comment by TimonPost** [comment]
the bug fix version is released: https://crates.io/crates/terminal
