### ISSUE TITLE
Getting the terminal size leaks fd in unix

### ISSUE THREAD

**Issue by jonathandturner** [crossterm-rs/crossterm#382]
**Describe the bug**
If you keep getting the terminal size, you'll leak enough file descriptors that the program will rash

**To Reproduce**
1. A tight loop where you check for the terminal size

**Expected behavior**
The file descriptors should get automatically close when you're finished them.

**OS**
Unix

**Terminal/Shell**
Bash/Nushell

**Comment by TimonPost** [comment]
#383 is merged, thanks for the report.
