### ISSUE TITLE
Panic From `crossterm::terminal::size`

### ISSUE THREAD

**Issue by zicklag** [crossterm-rs/crossterm#384]
**Describe the bug**
I'm getting a panic when calling `crossterm::terminal::size()`. I think it may only happen when the input is not a `tty`, which is the case in some instances in my execution environment, which is as a utility in scripts. Here is the crossterm section of the backtrace:

```
File "src/libcore/option.rs:1211", in core::option::expect_none_failed
File "<unknown>:0", in core::result::Result<T,E>::unwrap
File "<unknown>:0", in crossterm::terminal::sys::unix::size
File "<unknown>:0", in crossterm::terminal::size
...Frames for my code...

The application panicked (crashed).
   called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "No such device or address" }
in /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.16.0/src/terminal/sys/unix.rs:35
thread: main
```

---

It is arguable that I should not be calling `size()` when the input is not a TTY, but it seems like it still shouldn't panic. This only happened after I ran a `cargo update` and went from  crossterm `0.15` to `0.16`.

**To Reproduce**

Unfortunately, I can't figure out how exactly to reproduce on my local machine. The situations I run into the problem are on my CI server, when the CI build runs the command and when a [Juju](https://jaas.ai) server runs the command. I can't figure out how to simulate the broken or nonexistent tty in my shell, if that's really what's happening.

Hopefully that and the stack trace is enough to go off of. Tell me if there is something else I could do to help reproduce it. I just don't know enough about terminals yet. :slightly_smiling_face: 

**Expected behavior**
The process should not panic.

**OS**
 - Linux: Ubuntu 18.04

**Terminal/Shell**
 - None

**Comment by TimonPost** [comment]
You can use the https://crates.io/crates/atty to check if your library is running in an terminal.

**Comment by zicklag** [comment]
Added that check and it fixed it. :)

It would probably be good for `crossterm::terminal::size()` to return a Result if it wasn't a tty.

**Comment by TimonPost** [comment]
It certainly would fix it, it was discussed before, let's add it to the feature list.
