### ISSUE TITLE
Colors not implemented for single characters

### ISSUE THREAD

**Issue by PeterHindes** [crossterm-rs/crossterm#385]
**Describe the bug**

**To Reproduce**
1. Properly import `crossterm::style::Colorize`
2. Create a char
3. Try to colorize it

**Demo Code**
```rust
use std::io::{stdout, Write};

use crossterm::{
    execute,
    style::{Colorize,PrintStyledContent},
};

fn main() {
    let f = 'f';
    let fric = "fric";
    execute!(
        stdout(),
        PrintStyledContent(fric.cyan())
    );
    execute!(
        stdout(),
        PrintStyledContent(f.cyan())
    );
}
```

**Expected behavior**
Color is applied and printed like a &str.

**OS**
 - Windows

**Terminal/Shell**
 - Cargo Compile Error
 - `cargo run`

```rust
error[E0599]: no method named `cyan` found for type `char` in the current scope
  --> src\main.rs:60:84
   |
60 |                 stdout.queue(PrintStyledContent( (board_row_current[prin] as char).cyan() ))?;
   |                                                                                    ^^^^ method not found in `char`

error: aborting due to previous error
```

**Comment by TimonPost** [comment]
Thanks, it is indeed not yet implemented for characters. It can be. A similar thing as done here: https://github.com/crossterm-rs/crossterm/blob/master/src/style.rs#L162 should be done for char.

**Comment by PeterHindes** [comment]
Alright I think this [pull request](https://github.com/crossterm-rs/crossterm/pull/386) works.
