### ISSUE TITLE
Concat For Stylized str

### ISSUE THREAD

**Issue by PeterHindes** [crossterm-rs/crossterm#387]
**Is your feature request related to a problem? Please describe.**
I am trying to construct a stylized str for a game board that I want to print. Currently [StyledContent](https://docs.rs/crossterm/0.16.0/crossterm/style/struct.StyledContent.html) doesn't implement a String type or an equivalent to the `concat!()` macro. I don't see how I can do this without either feature.

**Describe the solution you'd like**
I would like a `styled_concat!()` macro and a version of StyledContent that will let me manipulate it like the regular `String` type in rust.

**Describe alternatives you've considered in any**
I could print my game board character by character and conditionally apply the formatting during the output, but that is slower and less understandable as code.

**Additional context**
This is for a tic-tac-toe board which will have colored places based on which players piece is in it. For example Orange for the X'es and Blue for the O's.

**Comment by PeterHindes** [comment]
Is there somewhere where I can direct message the maintainer? I want to ask some questions about how the StyledContent class works.

**Comment by PeterHindes** [comment]
Does the StyledContent only store one style/color configuration for a string, or can you store for example a string with a red word and a blue word?

**Comment by TimonPost** [comment]
You can join the discord, I am almost always there.

**Comment by PeterHindes** [comment]
Cool, where can I find that?

**Comment by TimonPost** [comment]
Feel free to join here: https://discordapp.com/invite/K4nyTDB, I guess I'll answer your questions above directly instead of doing it here.

**Comment by TimonPost** [comment]
If you think it is still relevant feel free to reopen.
