### ISSUE TITLE
`terminal::size` fails in Visual Studio Code

### ISSUE THREAD

**Issue by joshhansen** [crossterm-rs/crossterm#393]
**Describe the bug**
Calls to `terminal::size` fail when run in Visual Studio Code on Linux in Crossterm 0.16.0.

The equivalent functionality did not seem to provoke an error under Crossterm 0.11 which I am currently porting from, so this seems to be a regression. (I was actually porting to see if #253 which I previously filed would be resolved with the recent revisions in the architecture of this library.)

Maybe VSCode is interacting in a non-standard way with its embedded terminal? I understand it's not necessarily possible for Crossterm to support every development environment out there, but this is a fairly common one especially in Rust development.

This occurs both with the internal terminal, and with the external terminal option VSCode provides. It was set to use `urxvt`. When I run this code in `urxvt` directly, there is no problem, so the difficulty does seem to be VSCode related.

I'm happy to report that the upgrade to 0.16.0 has otherwise been fairly painless :-)

**To Reproduce**
With crossterm 0.16.0, run or debug this code inside Visual Studio Code on Linux:

```
use crossterm::terminal::size;

fn main() {
    size().unwrap();
}
```

**Expected behavior**
This should run normally.

Instead I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "No such device or address" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**OS**
Fedora 30 x86_64

**Comment by TimonPost** [comment]
Maybe it is related to: #362 which was introduced in 0.16. The code for reading the terminal size can be found [here](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal/sys/unix.rs#L26). I think that this is related to `/dev/tty` not being available from the vs code console. Currently returns an error, it should probably fall back on libc::STDOUT ([old version](https://github.com/crossterm-rs/crossterm/blob/9da9c1f5adedbf7dbb6c3480289eea0b00f24264/src/terminal/sys/unix.rs#L38)) when this file isn't available.

**Comment by joshhansen** [comment]
Yes, I could see that /dev/tty code causing my issue. Fallback like you specified sounds reasonable.

**Comment by atanunq** [comment]
Hi! I have been using crossterm for a while and it's been great. However, my Github actions are failing because of this issue. What is its current status? Can I help with something to get it resolved?

**Comment by TimonPost** [comment]
Hi, yes, I am short on time so can't fix it now. You could however help. 

It is quite an easy fix:

see this comment: https://github.com/crossterm-rs/crossterm/issues/393#issuecomment-593096036.

1. Update the Linux code for reading the terminal size. 
This opens a filehandle to `/dev/tty` and panics when this file does not exist. The only thing that has to be updated here is an fall back to `libc::STDOUT_FILENO`. 

So basicly:
```
if Ok(fd) = File::open("/dev/tty") {
  // use this fd
}else {
 // use libc::STDOUT_FILENO
}
```

**Comment by atanunq** [comment]
Thank you for the pointers, I opened pull request!
