### ISSUE TITLE
event::read doesn't return until return/enter is pressed

### ISSUE THREAD

**Issue by ray-britton-mubaloo** [crossterm-rs/crossterm#395]
**Describe the bug**
Using `event::read()` allows the user to type in many characters and then when the user presses return the first character typed is returned.

**To Reproduce**
Run this code:
```
fn main() {
    println!("Waiting");
    match crossterm::event::read() {
        Ok(result) => println!("Result: {:?}", result),
        Err(err) => eprintln!("Error: {}", err),
    }
    println!("Done");
}
```
Then press any key except return, then press return
Output:
```
➜  crossterm_test git:(master) ✗ cargo run
Waiting
rafsdgafashsfd
Result: Key(KeyEvent { code: Char('r'), modifiers: (empty) })
Done
```

**Expected behavior**
Based on the documentation I would have expected `read()` to return immediately after pressing any key.

**OS**
macOS Mojave 10.14.6

**Terminal/Shell**
Terminal 2.9.5 (using zsh)

**Comment by TimonPost** [comment]
You need to enable raw mode `enable_raw_mode` this will disable line return and will write all input directly to the input buffer whereafter crossterm can read it.

**Comment by ray-britton-mubaloo** [comment]
Ok thanks.
I'd suggest it would be worth adding a sentence explaining that or a link to https://docs.rs/crossterm/0.16.0/crossterm/terminal/#raw-mode in the https://docs.rs/crossterm/0.16.0/crossterm/event/index.html
