### ISSUE TITLE
KeyModifiers and KeyCode::Enter

### ISSUE THREAD

**Issue by extrawurst** [crossterm-rs/crossterm#400]
**Describe the bug**
No Modifiers are provided for KeyEvent with the `Enter` Key. In fact in my test almost only the arrow keys provided the correct modifier keys. Looking at this code I am wondering if its actually only provided for the arrow keys:
https://github.com/crossterm-rs/crossterm/blob/e863b7b75fc2f0d510631c97bdc51d2d5102c9ee/src/event/sys/unix/parse.rs#L191-L200

**To Reproduce**
Running the `event-poll-read` example and pressing `SHIFT+ENTER` prints:
```
Event::Key(KeyEvent { code: Enter, modifiers: NONE })
```

**Expected behavior**
the correct modifier in the KeyEvent

**OS**
MacOS

**Terminal/Shell**
iTerm (Zsh)

**Comment by TimonPost** [comment]
![image](https://user-images.githubusercontent.com/19969910/77472910-e9d9fc80-6e14-11ea-9c13-3e3507d0d0a6.png)


It seems like this sequence is not supported by the terminal, unfortunately.
