### ISSUE TITLE
Support the cbreak mode

### ISSUE THREAD

**Issue by equal-l2** [crossterm-rs/crossterm#402]
**Is your feature request related to a problem? Please describe.**
I want to handle ordinary key inputs (e.g. 'a', '0' or 'Z') in manner of raw mode, but I want special keys (e.g. Ctrl+C) to be handled by terminal.

**Describe the solution you'd like**
Support cbreak mode.

**Describe alternatives you've considered in any**
None.

**Comment by TimonPost** [comment]
Is on the feature list if possible.

**Comment by DexterHaxxor** [comment]
Is this ever gonna be real?
