### ISSUE TITLE
Please improve handling of non-US keyboards. Here's how

### ISSUE THREAD

**Issue by hlavaatch** [crossterm-rs/crossterm#408]
Key events that correspond to unicode characters > 255 are presently ignored.
This makes for example half of top row of Czech keyboard not work.

Please replace the [None here](https://github.com/crossterm-rs/crossterm/blob/master/src/event/sys/windows/parse.rs#L111) with this to make most of the Unicode keys work:
```
		match std::char::from_u32(character_raw as u32) {
			Some(ch) => Some(KeyCode::Char(ch)),
			None => None
                }
```

This area of Windows is a bit of a mess; considering they are using only 16bit field it will not be perfect, but it should work for most of the languages.

**Comment by hlavaatch** [comment]
[PR with fix](https://github.com/crossterm-rs/crossterm/pull/411)

**Comment by TimonPost** [comment]
Merged, thanks for the collaboration!
