### ISSUE TITLE
A released middle or right mouse click is reported as left.

### ISSUE THREAD

**Issue by Jezza** [crossterm-rs/crossterm#412]
**Describe the bug**
It looks like that the right or middle mouse buttons are reported as left, but only when releasing.

**To Reproduce**
1. Compile:
```rust
use std::{
	io::{stdout, Stdout, Write},
	time::{Duration, Instant},
};
use crossterm::{
	execute,
	event::{
		self,
		EnableMouseCapture,
		Event,
		KeyCode,
		KeyEvent
	},
	terminal::{
		disable_raw_mode,
		enable_raw_mode
	}
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
	enable_raw_mode()?;

	let mut stdout = stdout();
	execute!(stdout, EnableMouseCapture)?;

	loop {
		if event::poll(Duration::from_secs(0))? {
			let event = event::read()?;
			println!("{:?}", event);
			if let Event::Key(KeyEvent {
								  code: KeyCode::Char('q'),
								  ..
							  }) = event {
				break;
			}
		}
	}

	disable_raw_mode()?;
	Ok(())
}
```
2. Run
3. Left click, middle click, right click.
4. Observe output:
![cmd_2020-04-06_10-18-56](https://user-images.githubusercontent.com/4224088/78537637-11a36a00-77f0-11ea-94f2-2a604f65799d.png)

**Expected behavior**
The event should contain the correct button that was released.

**OS**
Windows

**Terminal/Shell**
cmd

**Comment by TimonPost** [comment]
This is intentional. Windows does not register mouse button with an up event. One should keep track of the button pressed on key down and use that button for the up event as well. We decided to keep this logic out of crossterm because it introduced complexity. Cursive is a nice reference to see how this should be done.

**Comment by Jezza** [comment]
Ah, gotcha.

It definitely is easy enough to do a somewhat basic implementation.
I've had some problems with holding both right and left in, but it's been fine for now.

Ah, yeah, it is [documented](https://github.com/crossterm-rs/crossterm/blob/master/src/event.rs#L288-L289).
I should have gone through the docs first.
Thanks.
