### ISSUE TITLE
Inconsistent Documentation

### ISSUE THREAD

**Issue by Kixiron** [crossterm-rs/crossterm#414]
In the current [documentation] cursor position is documented inconsistently. The examples I've found are that in [`terminal::size()`](https://docs.rs/crossterm/0.17.2/crossterm/terminal/fn.size.html) it states that 

> The top left cell is represented `(1, 1)`.

but then in [`cursor::MoveTo`](https://docs.rs/crossterm/0.17.2/crossterm/cursor/struct.MoveTo.html) it says that 

> Top left cell is represented as `0,0`.

**Comment by TimonPost** [comment]
That's correctly documentated. The cursor position starts to count at 0 and the terminal size is the character count in width and height.

**Comment by TimonPost** [comment]
I will close it for now, if you have any comments feel free to re-open.
