### ISSUE TITLE
SHIFT + TAB KeyEvent is inconsistant between linux and windows

### ISSUE THREAD

**Issue by MCord** [crossterm-rs/crossterm#442]
**Describe the bug**
when in raw mode the KeyEvent that is read for `SHIFT + TAB` sequence is not the same for linux and windows platforms.

Linux : `KeyEvent { code: BackTab, modifiers: NONE }` 
Windows: `KeyEvent { code: BackTab, modifiers: SHIFT }` 

**To Reproduce**
I have used this code snippet to confirm the issue.

```
use crossterm::{terminal::{disable_raw_mode, enable_raw_mode}, event::{read, KeyCode, KeyEvent, KeyModifiers}};

fn main() {
    print_events().unwrap();
    disable_raw_mode().unwrap();
}

fn print_events() -> crossterm::Result<()> {
    loop {
        enable_raw_mode()?;

        match read()? {
            crossterm::event::Event::Key(KeyEvent {
                code: KeyCode::Esc, 
                modifiers: KeyModifiers::NONE}) => break,
            x => println!("{:?}", x),
        }
    }
    Ok(())
}
```

**Expected behavior**
The same value for both platfroms. Either the linux implementation should return 'SHIFT' as modifier or the windows implementation should return `NONE` as  modifier. 

**OS**
Windows 10 / Ubuntu 18.04.2 LTS

**Terminal/Console**
CMD / Windows Terminal on Windows
Bash on Ubuntu

**Comment by almindor** [comment]
Not sure if related but it seems SHIFT is "broken" in this way along possibly other modifiers? I just found out that trying to respond to a `:`-press event doesn't work in Windows but works in Linux. The event itself is built without a modifier so I suspect in windows it's being matched to a `:` + SHIFT modifier but on Linux it's just `:` + NONE
