### ISSUE TITLE
Feature: add Chars in KeyCode

### ISSUE THREAD

**Issue by D1mon** [crossterm-rs/crossterm#443]
```rust
crossterm::event::KeyCode {
  ...
  Chars(&str),
}
```
Need an opportunity to implement a few keystrokes:
```rust
Chars("gg"); // press 'g' and then 'g' again```

**Comment by TimonPost** [comment]
Ah but that's something the user is supposed to handle. Crossterm will only return combinations and individual keystrokes. It is difficult to integrate this kind of behavior into the core.
