### ISSUE TITLE
Queuing and WinApi

### ISSUE THREAD

**Issue by sigmaSd** [crossterm-rs/crossterm#445]
Consider this example:
```rust
queue!(stdout(), SetForegroundColor(Blue));
queue!(stdout(), Print("Hello World");
queue!(stdout(), ResetColor());
```
The expected behaviour is we get a blue coloured hello world, instead we get an uncoloured one(white)
This is because with winapi SetForgroundColor and ResetColor (and some other commands) are eagerly executed as you can see here https://github.com/crossterm-rs/crossterm/blob/master/src/macros.rs#L36, while Print() will only execute later after we flush the buffer as attested here https://docs.rs/crossterm/0.17.5/src/crossterm/style.rs.html#365 

If I recall correctly I remember that you stated before that winapi is not compatible with queuing system and will execute eagerly instead, so in that case a simple fix would be to change `print!` to `write! + flush` here https://docs.rs/crossterm/0.17.5/src/crossterm/style.rs.html#365

**Comment by sigmaSd** [comment]
Also side-note: considering https://github.com/crossterm-rs/crossterm/blob/master/src/macros.rs#L36 maybe `execute_winapi` should also take `$writer` as arg like `write_ansi_code` so we don't have to hard-code the output to `stdout` like it is the case currently

**Comment by sigmaSd** [comment]
Also another idea, maybe its a good practice to add a [compile_error!](https://doc.rust-lang.org/std/macro.compile_error.html) when queue is used with winapi, obviously it will need some refactoring since `execute!` uses `queue!` internally but its doesn't look too difficult.

This way the interaction between queuing and winapi becomes explicit, and this spares the library documenting it

**Comment by TimonPost** [comment]
> If I recall correctly I remember that you stated before that winapi is not compatible with queuing system

The main reason why this happened is because WINAPI calls are system calls and are not written to a 'writer'. This results in the fact that you cannot buffer them like we can with ANSI codes. 

> so in that case a simple fix would be to change print! to write! + flush here

This is not the functionality that is desirable, is it? Print' should be the same as 'print' and should not be executed immediately.

> maybe execute_winapi should also take $writer as arg like write_ansi_code so we don't have to hard-code the output to stdout like it is the case currently

I'm not sure I'm following you here. Namely, the WINAPI code has no idea of a writer and works completely without a 'writer'. Could you explain a little more?

**Comment by TimonPost** [comment]
As discussed in discord we can make `excute_winapi` accept a `write` parameter. Then we can pass the write instance that the user provides from the queue/execute macro down to the command. The command can in its turn use the user specified writer to perform actions on

**Comment by sigmaSd** [comment]
I gave it a try and refactoring this wasn't simple.
The problem is with `queue!` `$writer` needs to be `std::fmt::Formatter` because of `impl_display!` while `execute!` expects `$writer` to be `impl std::io::Write`, which are incompatible.

I suggest for now just replacing `print!()` with `write!(stdout()); stdout().flush()` so at least crossterm becomes usable on win7 again. (I would argue most usage is `stdout` anyway)

**Comment by sigmaSd** [comment]
To be clear about the issue:
If you use `execute_winapi(&self, writer: impl std::io::Write)`  this will fail https://github.com/crossterm-rs/crossterm/blob/master/src/macros.rs#L162

If you use `execute_winapi(&self, writer: impl std::fmt::Write)` this will fail https://github.com/crossterm-rs/crossterm/blob/master/src/macros.rs#L152

**Comment by sigmaSd** [comment]
Fixed in https://github.com/crossterm-rs/crossterm/pull/469
