### ISSUE TITLE
Windows Terminal Does not support Mouse events yet

### ISSUE THREAD

**Issue by luojia65** [crossterm-rs/crossterm#446]
**Describe the bug**
I tried crossterm examples on Windows today on `cmd`, `PowerShell` and the open source [`Windows Terminal`](https://github.com/microsoft/terminal). I used command `cargo run --example event-read` to capture keyboard, mouse and window resize. In `cmd` and `PowerShell`, all the three event types could be read normally. But in Windows Terminal, only keyboard and window resize could be read; mouse events seems like are not captured. What could happen here?

<details>
<summary>Cmd (works)</summary>

![image](https://user-images.githubusercontent.com/40385009/85030133-abec3a80-b1af-11ea-995c-d302953ec98b.png)

</details>
<details>
<summary>Powershell (works)</summary>

![image](https://user-images.githubusercontent.com/40385009/85029945-72b3ca80-b1af-11ea-9d95-86bbdab9956d.png)

</details>
<details>
<summary>Windows Terminal (no mouse event whenever I click on it)</summary>

![image](https://user-images.githubusercontent.com/40385009/85030519-1e5d1a80-b1b0-11ea-900d-25af5410dc35.png)

</details>

**To Reproduce**
1. Run `cargo run --example event-read` on Windows Terminal
2. Mouse click on window
3. No event output

**Expected behavior**
There should be mouse events in the output

**OS**
 - Windows

**Terminal/Console**
 - Windows Terminal

**Comment by TimonPost** [comment]
Make sure to enable the mouse capture with `EnableMouseCapture` command.

**Comment by luojia65** [comment]
I used the example directly, it seems like this example code has already executed this command: https://github.com/crossterm-rs/crossterm/blob/5f1cbdeda4eaa4f36dcf9240a72ec0b92b45738b/examples/event-read.rs#L46

**Comment by TimonPost** [comment]
Interesting, I am on a linux system, im a fraid that I cant validate the bug you are experiencing.

**Comment by luojia65** [comment]
@TimonPost I don't know if this terminal does not support mouse input by purpose or not. If this could be considered a bug, we may send issue to open source Windows Terminal project, or check out if there were mistakes in our crossterm project. If not, we may write it down into docs as compability notes.

**Comment by VladimirMarkelov** [comment]
A little more info. It looks like Windows Terminal does not support firing mouse events for a client applications: https://github.com/microsoft/terminal/issues/376

**Comment by NicTanghe** [comment]
Hello,

4 me, it reads everything just fine when using the asynchronous example.
Maybe Microsoft fixed this and it can be closed. (using windows terminal)

**Comment by teohhanhui** [comment]
Yes, it was fixed: https://github.com/microsoft/terminal/pull/9970#issuecomment-880059929

**Comment by TimonPost** [comment]
Cool than I close this issue.
