### ISSUE TITLE
use keyboard-types 

### ISSUE THREAD

**Issue by prabirshrestha** [crossterm-rs/crossterm#450]
Based on this https://www.reddit.com/r/rust/comments/hi9aq2/platform_keyboard_event_handling/, seems like druid is moving to [keyboard-types](https://crates.io/crates/keyboard-types) trait. Would be good to align here and would avoid learning new apis.

**Comment by TimonPost** [comment]
I am not sure if this is something we want. Looking at: https://docs.rs/keyboard-types/0.5.0/keyboard_types/enum.Key.html there are a lot of keys that are not supported by corssterm. This might confuse users right?

**Comment by prabirshrestha** [comment]
closing since wezterm also might not use. unless everyone uses it doesn't make sense. https://github.com/wez/wezterm/issues/237
