### ISSUE TITLE
I think crossterm::cursor::MoveRight(0) should not move the cursor

### ISSUE THREAD

**Issue by sunshinewithmoonlight** [crossterm-rs/crossterm#457]
crossterm::cursor::MoveRight(0) moves the cursor one position to the right instead of zero.  
I want to know if 0 really works when I move the cursor right by 1 to 0？

**Comment by TimonPost** [comment]
Agree, if this is the case it should not move the cursor position.

**Comment by MichaelMcDonnell** [comment]
Similarly, doing either MoveLeft(0) or MoveLeft(1) also moves to the left by 1 which is confusing.

**Comment by TimonPost** [comment]
Implemented by #476
