### ISSUE TITLE
SHIFT + SPACE doesn't work

### ISSUE THREAD

**Issue by acheronfail** [crossterm-rs/crossterm#460]
**Describe the bug**

`crossterm` fails to recognise that the `shift` modifier is pressed when the `space` key is pressed.

**To Reproduce**

```
cargo run --example event-read
# now press SHIFT + SPACE
```

You'll see that other modifiers like `CONTROL` work, but `SHIFT` does not.

**Expected behavior**

`crossterm` should be able to recognise the `SHIFT` modifier when pressing the `space` key.

**OS**
 - Linux `5.7.7-arch1-1`

**Terminal/Console**
 - `kitty`
 - `Konsole`

**Comment by TimonPost** [comment]
Can you validate if this error also occurs with the 0.17.5 version?

**Comment by acheronfail** [comment]
```bash
$ git checkout 0.17.5
$ cargo run --example event-read
Compiling signal-hook v0.1.16
   Compiling crossterm v0.17.5 (/tmp/crossterm)
    Finished dev [unoptimized + debuginfo] target(s) in 2.01s
     Running `target/debug/examples/event-read`
Blocking read()
 - Keyboard, mouse and terminal resize events enabled
 - Hit "c" to print current cursor position
 - Use Esc to quit

Event: Key(KeyEvent { code: Char('M'), modifiers: SHIFT })
Event: Key(KeyEvent { code: Char(' '), modifiers: NONE })
Event: Key(KeyEvent { code: Char(' '), modifiers: NONE })
Event: Key(KeyEvent { code: Char(' '), modifiers: NONE })
Event: Key(KeyEvent { code: Char(' '), modifiers: NONE })
Event: Key(KeyEvent { code: Esc, modifiers: NONE })
```

Yep, also doesn't work.

**Comment by sigmaSd** [comment]
This appears to be  a limitation of unix terminal emulators (they don't distinguish between Space and Shift-Space).
https://unix.stackexchange.com/questions/88579/shift-space-in-less

**Comment by TimonPost** [comment]
Fortunately, it doesn't relate to the new mio release. Depending on the terminals that your using there can be  quite some limitations. Because this is an limitation of the terminal as the link above show we can close this issue.
