### ISSUE TITLE
Queued commands might get overwritten on Windows if not flushed

### ISSUE THREAD

**Issue by Zapeth** [crossterm-rs/crossterm#472]
**Describe the bug**
Queued commands might get overwritten on Windows if not flushed.

**To Reproduce**
Of this sample sequence of queued commands several are skipped/overwritten by subsequent ones, leading to an incorrect result:
```
let (x_size, y_size) = size()?;
stdout()
    .queue(Clear(ClearType::FromCursorUp))?
    .queue(SavePosition)?
    .queue(MoveTo(1, 2))? // use execute for consistent positioning on windows
    .queue(SetForegroundColor(Color::Red))?
    .queue(SetBackgroundColor(Color::Blue))?
    .queue(Print("testing croßterm"))?   // use execute for consistent coloring on windows
    .queue(RestorePosition)?
    .queue(MoveToColumn(14))?        // use execute for consistent positioning on windows
    .queue(SetBackgroundColor(Color::Red))?
    .queue(SetForegroundColor(Color::Blue))?
    .queue(Print("another croßterm test"))?   // use execute for consistent coloring on windows
    .queue(ResetColor)?;
println!("\nx_size: {}, y_size: {}", x_size, y_size);
```

**Expected behavior**
If the marked `queue` commands of the above code are changed to `execute`, the output is as expected (though I somewhat doubt that this covers all the relevant cases).
This is not a problem when using mintty as a terminal (haven't checked Linux terminals, but I expect them to work properly in this regard as well).

I'm not sure if this is intended behavior or if it can be easily fixed, but it should be at least be mentioned as a (current) limitation in the documentation.

**OS**
Windows 7

**Terminal/Console**
cmd/Powershell

**Comment by sigmaSd** [comment]
Hi this issue is fixed in master, can you try again with crossterm pulled from git and report back ?

**Comment by Zapeth** [comment]
Indeed, both Powershell and cmd seem work properly when using the git version.

Would be nice to have the fix in an official release though (I'd like to avoid fetching entire repositories when possible).

**Comment by TimonPost** [comment]
Good one, I'll do a release soon
