### ISSUE TITLE
Support mintty under Windows

### ISSUE THREAD

**Issue by Zapeth** [crossterm-rs/crossterm#473]
**Is your feature request related to a problem? Please describe.**
`terminal::size()` reports incorrect terminal dimensions (80, 25 - the default Windows cmd dimensions) when launching from a mintty instance, presumably because `crossterm/src/terminal/sys/windows.rs` only uses native Console api functions?

Other commands/features might also be affected, I haven't done extensive tests (though at least basic commands like coloring and cursor positioning seem to work properly).

**Describe the solution you'd like**
The code in `crossterm/src/terminal/sys/windows.rs` should include checks/code for non-native Windows consoles where necessary in order to ensure proper results when using such terminals.

**Additional context**
I put this as a feature request since mintty wasn't listed under the "Tested Terminals" list.

**edit:** Just noticed that non-ascii characters are also not properly displayed in mintty, example `tästÜng croßter€` displays `t├ñst├£ng cro├ƒterΓé¼` (is displayed correctly in cmd/Powershell)

**Comment by TimonPost** [comment]
see: https://github.com/crossterm-rs/crossterm/issues/580
