### ISSUE TITLE
Mistake in event poll example

### ISSUE THREAD

**Issue by koutoftimer** [crossterm-rs/crossterm#478]
https://github.com/crossterm-rs/crossterm/blob/master/examples/event-poll-read.rs#L34

There are no `Into` implementation for KeyCode, only [`From`][from] for KeyEvent.

[from]: https://github.com/crossterm-rs/crossterm/blob/master/src/event.rs#L360

**Comment by TimonPost** [comment]
There is no mistake here, see the docs on `From` implementation. 

```
One should always prefer implementing From over Into because implementing From automatically provides one with an implementation of Into thanks to the blanket implementation in the standard library.
```
