### ISSUE TITLE
Reset Foreground/Background color

### ISSUE THREAD

**Issue by truchi** [crossterm-rs/crossterm#482]
Should be easy:
- add `Color::ResetForeground` (39) & `Color::ResetBackground` (49)
- reset colors properly in `StyledContent::fmt`
- remove `Color::Reset`, `ResetColor` & `RESET_CSI_SEQUENCE`?

Do you want me to do it?

Edit: Oh wait, it's actually #2 only!

**Comment by truchi** [comment]
Heck I'm doing it.

**Comment by TimonPost** [comment]
Merged, new issue is to be created for attributes individual resetting
