### ISSUE TITLE
(Regression) Crossterm 0.17.8 broke tui-rs 0.10 on Windows

### ISSUE THREAD

**Issue by alvinhochun** [crossterm-rs/crossterm#484]
**Describe the bug**
Attempting to build [tui-rs](https://github.com/fdehau/tui-rs) 0.10 or master with the crossterm backend on Windows fails:

```
error[E0599]: no method named `flush` found for struct `std::string::String` in the current scope
  --> src\backend\crossterm.rs:65:27
   |
65 |                 map_error(queue!(string, MoveTo(x, y)))?;
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `std::string::String
```

The apparent cause is due to the changes in PR #469.

However the real issue is the mismatched expectations between `crossterm` and `tui-rs` regarding the `handle_command` macro that has lead to this breaking change. It seems that `tui-rs` assumes that `handle_command` simply writes ANSI codes, not accounting for the case that `handle_command` may simply execute actual WinAPIs instead. On the other hand, `crossterm` did not account for the possibility that other writers that doesn't support `flush` (e.g. `std::fmt::Write` may be passed to `handle_command`.

See also: https://github.com/fdehau/tui-rs/issues/373

**To Reproduce**
1. Clone `tui-rs`
2. Run `cargo run --example crossterm_demo --no-default-features --features="crossterm"`

**Expected behavior**
There shouldn't be any compile errors.

**OS**
Windows

**Terminal/Console**
n/a

**Comment by alvinhochun** [comment]
I believe the `handle_command` macro should enforce the `std::io::Write` trait implementation on the `$writer` regardless of platform. It might also need an extra check to see if the `$writer` is `stdout` before calling any of the WinAPI console functions.

**Comment by Yatekii** [comment]
Can confirm: https://github.com/probe-rs/cargo-embed/runs/1089518571?check_suite_focus=true

:( Patch versions should be non breaking ...

**Comment by extrawurst** [comment]
> Attempting to build [tui-rs](https://github.com/fdehau/tui-rs) 0.10 or master with the crossterm backend on Windows fails:

let me add to this: this breaks `0.9.5` in the same way, which is bad if we only fix it for `0.10` because I know the upgrade from `0.9` to `0.10` is tough and not everyone will be able to to migrate

**Comment by TimonPost** [comment]
![image](https://user-images.githubusercontent.com/19969910/92729902-50c38180-f373-11ea-9537-6d93d0c4fc68.png)

I am on linux it seems to work. Perhaps it is a windows only issue. If it is an api breaking change would yanking the latest crossterm be a solution?

**Comment by TimonPost** [comment]
Before we accepted both, now we have limited to std::io::Write, that to me, seems like a API change. I should have released a major version and thus will do that in an up-comming version. I will yank this version and release a 0.18. I will validate, as you mentioned, for other breaking changes. Thanks for the help!

**Comment by TimonPost** [comment]
Yanked,  it.

**Comment by Yatekii** [comment]
Thank you very much, sir! Great experience with your service =)
