### ISSUE TITLE
Terminfo support?

### ISSUE THREAD

**Issue by Koxiaet** [crossterm-rs/crossterm#495]
For maximim portability across Unix systems Crossterm should use terminfo/termcap to find the terminal's escape codes and only fall back to xterm's when they cannot be determined. It's not completely necessary as most terminals work fine with xterm-like, but it would help supporting every single terminal.

This would also open the door for a function to check whether a certain command is supported on this terminal.

**Comment by TimonPost** [comment]
Interesting idea, I have been thinking about it. I don't have an opinion on it.

**Comment by Koxiaet** [comment]
Ah, I'm running into an issue: Crossterm's `Color` support 8 dark colors, 8 light colors, 240 ANSI colors and 16 million RGB colors. On the other hand Terminfo supports 8 colors, and then you can define your own RGB colors with an index (which also means using a global `HashMap`, not good). Collapsing both dark and light colors into one or assigning arbitrary RGB values to the 8 colors on Terminfo would cause different behaviour in ANSI vs terminfo mode, which is absolutely not what we want, but removing the 8 variants and the `AnsiValue` variant is a large breaking change and pretty major loss of functionality.

What do you think @TimonPost? Is it even _worth_ supporting Terminfo?

**Comment by TimonPost** [comment]
It doesn't seem to be adding much value in that regard and I don't see the reason to change this.

**Comment by Koxiaet** [comment]
I'll close this then. It's a shame, terminfo is a good idea, it's just too outdated.
