### ISSUE TITLE
Backspace with modifiers not recognised as backspace

### ISSUE THREAD

**Issue by fabi321** [crossterm-rs/crossterm#504]
**Describe the bug**
If I press backspace together with a modifier like ctrl or shift, it gets interpreted as char + modifier.

**To Reproduce**
1. Go to https://gitlab.com/kuenstler/yint-rs
2. compile and run it
3. press any modifier + backspace

**Expected behavior**
In case of ctrl + backspace, it should delete unicode words. in other cases it should delete the last unicode grapheme.

**OS**
 - Linux

**Terminal/Console**
 - VSCode terminal: ctrl -> w, shift -> h, alt -> delete (0x7f)
 - Konsole: ctrl -> h, shift -> backspace, alt -> delete (0x7f)
 - Ubuntu console window: like Konsole

**Language**
German

**Comment by TimonPost** [comment]
I can not give you a definitive answer. Terminal input sequence codes are terrible to work with. Your language, key-board layout can play a role here. However, if you enable raw mode keep in mind any behavior like deleting the last word will not work anymore. It's your responsibility to get it to work.

**Comment by fabi321** [comment]
Yeah, of course, I implemented something that works on ctrl + backspace and it never receives any ctrl + backspace. That's some custom behavior I programmed, but it never gets to action since it never gets any ctrl + backspace.

**Comment by fabi321** [comment]
on Konsole, ctrl + backspace yields ^H (08), while on VSCode, ctrl + backspace yields ^W (17)

**Comment by TimonPost** [comment]
Hrm... 

Looking through some terminal sequence documentation I see that `^ H` represents backspace with the 0X08 hex code, in vt100 terminals.  https://www.real-world-systems.com/docs/ANSIcode.html 

I will have to dive into the ANSI code parsing to see why this is not throwing a backspace. It could be the case it is not yet supported in combinations with CTRL.

**Comment by fabi321** [comment]
As far as I've understood the /src/event/sys/unix/parse.rs code, the following lines in parse_event
```rust
        c @ b'\x01'..=b'\x1A' => Ok(Some(InternalEvent::Event(Event::Key(KeyEvent::new(
            KeyCode::Char((c as u8 - 0x1 + b'a') as char),
            KeyModifiers::CONTROL,
        ))))),
```
(line 83 and following)
are responsible for those characters

**Comment by fabi321** [comment]
I wrote a possible solution at #506 , feel free to change the style. It's throwing some warnings at b'\x09' and b'\x0d'

**Comment by fabi321** [comment]
Maybe it wold be a cleaner solution, if one added another KeyCode type ControlCode to raise the programmers awareness for other control codes like ^W (which I hardcoded to ctrl + backspace).

**Comment by David-Else** [comment]
Could someone fix this? It is a real show stopper for people used to the `ctrl backspace` for deleting a word shortcut.

**Comment by coloradocolby** [comment]
Also would love to see this added! Was banging my head against the wall trying to figure out why there were no modifiers when I hit backspace until I realized this just wasn't supported lol

**Comment by TimonPost** [comment]
Closing in favour of https://github.com/crossterm-rs/crossterm/issues/685.
