### ISSUE TITLE
Question: how to get correct terminal window size on Windows?

### ISSUE THREAD

**Issue by VladimirMarkelov** [crossterm-rs/crossterm#507]
Windows 10 20H2.

I added `Event::Resize(width, height)` handler. At my side, by default it works well only for new Windows Terminal. For `cmd` and `powershell` the size is the size of the buffer, not the terminal window.

I use a workaround like this:

```
Event::Resize(_, _) => {
    let (width, height) = terminal::size().unwrap();
```

Is there a better way? I found a public function `parse_relative_y`. It is windows only and it is deep in source tree. I am not sure if it a good way to solve the issue.

Thank you!

**Comment by TimonPost** [comment]
That's a good question. Depending on what linux returns when this even happens we want to return the terminal size here. So if this is tot the case a change is needed. What you do now is a good alternative way of doing it.

**Comment by TimonPost** [comment]
https://github.com/crossterm-rs/crossterm/blob/master/src/event/source/unix.rs#L140

Linux does return the normal terminal size. So windows should as well

**Comment by TimonPost** [comment]
Over here crossterm gets the buffer size. This should be changed to terminal dimensions instead. https://github.com/crossterm-rs/crossterm-winapi/blob/master/src/structs/input.rs#L281

**Comment by sigmaSd** [comment]
related https://github.com/crossterm-rs/crossterm/issues/466

**Comment by VladimirMarkelov** [comment]
> Related #466

Yes, it is the same. Sorry for creating a duplicate. Though, #466 title seems misleading to me(that was why I ignored it when looked through issues to see if anyone had opened the similar issue): it states that "event is not fired" but inside it explains that the numbers are incorrect.

**Comment by sigmaSd** [comment]
Dont worry about it.
I just add it so we know which issues to close when this is fixed.

**Comment by TimonPost** [comment]
I fixed the wrong size return. I will make a PR soon.
