### ISSUE TITLE
Please add support for more modifier keys

### ISSUE THREAD

**Issue by lebensterben** [crossterm-rs/crossterm#510]
Currently the modifier keys supported are:
- Shift
- Ctrl
- Alt

Please consider adding support for the following modifier keys
- Super
- Hyper
- Meta
- ISO/IEC 9995 Level 3 Shift

Among them, Super is often mapped to Win key by graphical display manager. And Meta are commonly mapped to level 2 of Alt, i.e. Meta = Shift + Alt.

Hyper and Level 3 Shift are less commonly used but can be very useful to avoid conflicts of keybindings with other programs.

**Comment by pianohacker** [comment]
Can this be closed with the addition of the [keyboard enhancement feature](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html) to 0.25?

**Comment by lebensterben** [comment]
Amazing!
