### ISSUE TITLE
crossterm::event::read requires raw input on WSL

### ISSUE THREAD

**Issue by dsherret** [crossterm-rs/crossterm#521]
**Describe the bug**

The `crossterm::event::read` function does not return on keypress on WSL, but works fine on Windows not in WSL. On WSL it shows stuff like "^[[A" or whatever key is pressed.

Is this expected? My current workaround is to go into raw mode:

```rs
pub(crate) fn read_terminal_event() -> Result<Event, ErrBox> {
    terminal::enable_raw_mode()?;
    let result = read();
    terminal::disable_raw_mode()?;

    match result {
        Ok(Event::Key(KeyEvent {
            code: KeyCode::Char('c'),
            modifiers: KeyModifiers::CONTROL
        })) => std::process::exit(1),
        _ => Ok(result?),
    }
}
```

**To Reproduce**

```ts
let event = crossterm::event::read()?
```

**Expected behavior**

Crossterm handles the environment differences for me and I don't need to manually go into raw mode.

**OS**
 - WSL on windows Windows

**Terminal/Console**
 - Windows Terminal, but also happens in cmd

**Comment by TimonPost** [comment]
Yes that is expected. Raw mode is required for reading input.

**Comment by dsherret** [comment]
@TimonPost ok, thanks! I wonder what could be done to make this more obvious. I was developing on windows and so it worked without enabling raw mode and I didn't know there would be issues on other platforms. Perhaps we could update the documentation for [`read`](https://docs.rs/crossterm/0.18.2/crossterm/event/fn.read.html) to include a note that `crossterm::terminal::enable_raw_mode()` should be called first? I wouldn't mind opening a PR.

Alternatively, do you think there is any way for crossterm to handle this automatically? I wonder if perhaps if someone is not in raw mode then it could go to raw mode, do a read, then drop back out of raw mode after. I think it would be a breaking change though because right now on windows this works without going into raw mode and so ctrl+c works for killing the app in that scenario, but wouldn't work after this change. Perhaps this is too much trouble to handle automatically?

**Comment by TimonPost** [comment]
In the past crosterm used to work that way, we moved away from it because it requires keeping state. I prefer to leave that over to the user it was quite difficult to decide when to disable raw mode. It's perfect to open a PR of that. I can do that today.

**Comment by file-acomplaint** [comment]
Just wanted to add that I had the same problem today by developing on Windows and ending up with a total mess on UNIX.

I have no idea how you folks do this magic, but as a simple user's opinion: Would it be better to require raw mode on windows as well, since it completely breaks the other platform? Crossterm seems to be all about cross-platform, so I was a little frustrated at first. Thanks for the great library though!
