### ISSUE TITLE
Ctrl + _ registers as Ctrl + 7

### ISSUE THREAD

**Issue by demmel** [crossterm-rs/crossterm#540]
When using raw mode Key Events in crossterm, it looks I'm incorrectly get Ctrl+7 when I hit Ctrl+_.  It looks like Rustyline is able to correctly interpret the keycode for this sequence here https://github.com/kkawakam/rustyline/blob/master/src/keys.rs#L67.  I'm not sure if there's more to it than that, but perhaps crossterm could do this as well.  Otherwise, crossterm's EventStream has been awesome for handling async input in rawmode!

**Comment by demmel** [comment]
Oops, it looks like this may be a dupe of #536.

**Comment by demmel** [comment]
Looks like #536 is about a specific issue on Windows though.  I'm experiencing this on a unix terminal.

**Comment by TimonPost** [comment]
Yes windows not related to this issue. Thanks for sharing that link, the ANSI code parsing code has to be altered to support this key combination.

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/crossterm-rs/crossterm/issues/685.
