### ISSUE TITLE
Bracketed Paste Events

### ISSUE THREAD

**Issue by bhgomes** [crossterm-rs/crossterm#545]
**Is your feature request related to a problem? Please describe.**
I want to be able to process input that contains line feeds. Allowing the terminal to enter [bracketed paste mode](https://cirw.in/blog/bracketed-paste) allows us to buffer an incoming paste and collect non-`Enter` line feeds. This is already a standard feature of many terminal emulators. 

**Describe the solution you'd like**
- Add the relevant enable/disable pair: `enable_bracketed_paste` (`EnableBracketedPaste`) and `disable_bracketed_paste` (`DisableBracketedPaste`), either to global scope or to the terminal depending on the unix/windows implementation details.
- Here are a few options for formatting the paste:
  - [1] Add `Event::Paste` variant that holds the entire pasted string
  - [2] Add `KeyCode::BracketedPasteStart` and `KeyCode::BracketedPasteEnd` variants and allow the user to access escape codes so that they can implement paste filtering themselves (not very user-friendly) or another part of this library will do the paste filtering.
- Because both of these options change the enum interfaces, we can probably put this behind an optional feature.

**Describe alternatives you've considered in any**
An alternative is to use something like [`rustyline`](https://github.com/kkawakam/rustyline) to handle shell-like input, and only use `crossterm` to handle other kinds of interaction. The problem with something like [`rustyline`] is that it [only allows stdin/stdout](https://github.com/kkawakam/rustyline/issues/377) as far as I am aware and won't be able to implement something like the following "half-shell":

```
-----------------------------
|             |             |
|  [shell     |             |
|  output]    |   [other    |
|             |   widget]   |
|-------------|             |
| > [prompt]  |             |
-----------------------------
```

where the `[other widget]` can read arrow key and other non-text inputs (i.e. how is [`rustyline`] supposed to know that the input should wrap only at half the terminal width?). Also, multi-panel input components like [`tui-rs`](https://github.com/fdehau/tui-rs) widgets. See [this issue](https://github.com/kkawakam/rustyline/issues/494) for other compatibility issues with [`rustyline`](https://github.com/kkawakam/rustyline).

**Additional context**
- The [`termwiz`](https://crates.io/crates/termwiz) crate has a similar kind of [`InputEvent`](https://docs.rs/termwiz/0.11.0/termwiz/input/enum.InputEvent.html) as solution [1].
- The [`rustyline`](https://github.com/kkawakam/rustyline) crate has a similar kind of [`KeyCode`](https://docs.rs/rustyline/8.0.0/rustyline/enum.KeyCode.html) as solution [2].
- The Microsoft terminal [just added support](https://github.com/microsoft/terminal/pull/9034) for this feature.

**Comment by TimonPost** [comment]
Fixed by: #693
