### ISSUE TITLE
How to enter raw mode?

### ISSUE THREAD

**Issue by tech0tron** [crossterm-rs/crossterm#546]
I looked through the documentation and the examples repository to no avail. What is the command or function or macro or whatever to easily enter in and out of raw mode? I tried doing `use crossterm::{RawScreen};` but it says it doesn't exist. I am very new to Rust, go gentle.

**Comment by bradms** [comment]
Is what you're looking for [here](https://docs.rs/crossterm/0.19.0/crossterm/terminal/#raw-mode)?

There's some functions for entering and exiting raw mode from a glance [`enable_raw_mode`](https://docs.rs/crossterm/0.19.0/crossterm/terminal/fn.enable_raw_mode.html) and a corresponding [`disable_raw_mode`](https://docs.rs/crossterm/0.19.0/crossterm/terminal/fn.disable_raw_mode.html)

**Comment by tech0tron** [comment]
ahah! I thought i needed to use rawscreen, thank you, turns out I was on wrong docs version.
