### ISSUE TITLE
How can I use this library to develop a similar grammar prompt function?

### ISSUE THREAD

**Issue by yancheng199287** [crossterm-rs/crossterm#549]
crossterm is a good terminal library.
Recently I want to use it to develop a shell terminal.
I want to add a grammar prompt to it. Just like bash, you can press the tab key to trigger a grammar prompt. How can I use this library to develop a similar grammar prompt function?

**Comment by TimonPost** [comment]
For the best inspiration, you can visit the libraries linked in the readme. There are several applications out that deal with terminal as editor.

**Comment by TimonPost** [comment]
Closing as of topic
