### ISSUE TITLE
Adding an Eq implementation for StyledContent

### ISSUE THREAD

**Issue by abrassel** [crossterm-rs/crossterm#559]
**Is your feature request related to a problem? Please describe.**

I am building a TUI on top of crossterm, and I would like to be able to test output by comparing `StyledContent` structs against each other.  My current workaround is a helper method that asserts two `StyledContent`s are equal iff they have the same, well, style and content.  

**Describe the solution you'd like**

This would be a helpful feature to have in `crossterm`, and I would like to be able to directly compare two `StyledContent`s without having to resort to said workaround.

I'm happy to submit a PR to add this functionality.

**Comment by TimonPost** [comment]
Fixed in 0.20!
