### ISSUE TITLE
High CPU overhead when polling

### ISSUE THREAD

**Issue by sayanarijit** [crossterm-rs/crossterm#560]
**Describe the bug**

Not sure if [this](https://github.com/crossterm-rs/crossterm/issues/397) is the real cause, or I'm doing something wrong, but any hint on how to optimize [this polling overhead issue](https://github.com/sayanarijit/xplr/issues/10) would be appreciated.

**To Reproduce**
1. `git clone https://github.com/sayanarijit/xplr`
2. `cargo flamegraph --bin xplr`
3. See the result.
4. Remove [polling](https://github.com/sayanarijit/xplr/blob/main/src/event_reader.rs).
5. `cargo flamegraph --bin xplr`
6. Compare the result.

**Expected behavior**
The CPU should not to be too high, yet it gets pretty high. Increasing the timeout makes the app less responsive. Not sure how `termion` does it, but I haven't faced CPU issue with `termion` even with async read.

**OS**
Manjaro latest

**Terminal/Console**
Alacritty

**Comment by sigmaSd** [comment]
Hello, 

You appear to be using poll with 1 millisecond duration in a synchronous code, isn't cpu usage expected to be high in this case?

I think a more correct solution would be to either increase polling duration or use async (example https://github.com/crossterm-rs/crossterm/blob/master/examples/event-stream-tokio.rs)

**Comment by sigmaSd** [comment]
Also since you're reading events in a different threads what is the purpose of polling?, does simply blocking for read in that thread doesn't work?

**Comment by sayanarijit** [comment]
The example uses the tokio runtime. I don't want to complicate things by introducing async runtime. Is there a way I can keep the asyncness isolated only to input reading?

**Comment by sayanarijit** [comment]
I think I can just not declare every function as async

**Comment by sigmaSd** [comment]
I think for async you will need to rewrite the codebase

I faced this before the trick that worked for me before is making the main thread controls when crossterm reads (std:thread:park after each read and the main thread unparks the crossterm thread when needed) but its definitly a hack

I guess we either need a solution to https://github.com/crossterm-rs/crossterm/issues/397 or using an async codebase in these cases is the right answer

**Comment by sayanarijit** [comment]
Got it. Closing this.

**Comment by sayanarijit** [comment]
For future readers, another simpler approach is to increase the sleep time when the key is not being held ([example](https://github.com/sayanarijit/xplr/pull/96/files)). But of course, this needs to be tested to see how it impacts the responsiveness of the program.
