### ISSUE TITLE
Add Cargo.lock file

### ISSUE THREAD

**Issue by akshgpt7** [crossterm-rs/crossterm#563]
**Is your feature request related to a problem? Please describe.**
I am packaging this library for [Nix](https://github.com/NixOS/nixpkgs/), and realized it doesn't have the `Cargo.lock` file, which is important for the build.
Per the instructions in the [Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) best practices guide, Rust applications should always commit the Cargo.lock file in git to ensure a reproducible build.

**Describe the solution you'd like**
Add the `Cargo.lock` file.

**Comment by sigmaSd** [comment]
Hello,

Libraries should not commit Cargo.lock (which is what is mentioned in the book)

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by akshgpt7** [comment]
Ah, thanks for the clarification. I'm still pretty new to Rust, so trying to get up to speed.

**Comment by sigmaSd** [comment]
You're welcome!
