### ISSUE TITLE
event polling example broken in windows git bash

### ISSUE THREAD

**Issue by extrawurst** [crossterm-rs/crossterm#568]
windows 10 and git-bash

```
cargo r --example event-poll-read
```

none of the expected events arrive:

https://user-images.githubusercontent.com/776816/117581070-3789f500-b0fb-11eb-8cad-52525091ab75.mp4

**Comment by TimonPost** [comment]
There are some other issues related to this problem. The problem is that winapi is not directly accessible through git bash on windows. I am not directly aware of howe we could potential fix this.

**Comment by TimonPost** [comment]
see: https://github.com/crossterm-rs/crossterm/issues/580
