### ISSUE TITLE
Support new terminal protocol for extended keys and more modifiers

### ISSUE THREAD

**Issue by maximbaz** [crossterm-rs/crossterm#569]
There is a new protocol that modern terminals will support, originally designed by fixterms and later adopted and finalized by kitty: https://sw.kovidgoyal.net/kitty/keyboard-protocol.html

Supporting this protocol will allow you to distinguish many more keys and modifiers (see the page for full list of benefits), and probably fix a bunch of open issues related to the modifiers.

**Comment by stevenxxiu** [comment]
I use *Broot*, and it does not detect `Ctrl + M`. This is probably related.

**Comment by TimonPost** [comment]
This was implemented by: #691 #696 #688
