### ISSUE TITLE
Incorrect color names in docs

### ISSUE THREAD

**Issue by tobx** [crossterm-rs/crossterm#573]
**Describe the bug**

In the docs at [Platform-specific Notes](https://docs.rs/crossterm/0.19.0/crossterm/style/enum.Color.html#platform-specific-notes) it says `DarkWhite` for the dark version of `White` and `Grey` for the light version of `Black`.

**Expected behavior**

The dark version of `White` should be `Grey` while the light version of `Black` should be `DarkGrey`. `DarkWhite` does not exist. At least this is how it is coded [here](https://github.com/crossterm-rs/crossterm/blob/b31782249e3ef1c2e5d8f2f668763fddb2e0a060/src/style/types/color.rs#L126).

Just for interest, AFAIK the ANSI colors are defined as "normal" (e.g. "red") and "bright" (e.g. "bright red"). In crossterm, why are the colors named "dark" (e.g. DarkRed) for normal ANSI colors and "normal" (e.g. Red) for bright ANSI colors?

**Comment by JamRemco** [comment]
in version 2.0 Color::White maps to the same as Color::Grey. 
In other words there is no color (bright) white.

**Comment by TimonPost** [comment]
I think
