### ISSUE TITLE
macOS, backspace, and modifiers

### ISSUE THREAD

**Issue by jntrnr** [crossterm-rs/crossterm#575]
**Describe the bug**
This seems related to #504. On macOS, if you do Ctrl+Backspace or Alt+Backspace, crossterm reports these as Backspace with no modifiers.

**To Reproduce**
1. Ctrl+Backspace
2. or
3. Alt+Backspace

**Expected behavior**
The correct modifiers are connect to the code.

**OS**
 - macOS

**Terminal/Console**
 - Standard macOS 10.15 terminal

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/crossterm-rs/crossterm/issues/685.
