### ISSUE TITLE
Release a newer version with deserialize function

### ISSUE THREAD

**Issue by zwpaper** [crossterm-rs/crossterm#582]
**Is your feature request related to a problem? Please describe.**
I would like to use crossterm with deserializing in https://github.com/Peltoche/lsd/pull/452

**Describe the solution you'd like**
Release a newer version with the deserialize function.

**Describe alternatives you've considered in any**
I was using the master currently.

**Additional context**
Anything else?

**Comment by TimonPost** [comment]
Crossterm already supports serde right? What is concrete result your looking for?

**Comment by zwpaper** [comment]
sorry for not explaining myself concretely, now that crossterm supports serde, but we can not use it as versioned crate, the newest one is 0.20.0 without serde support.

So I hope that a newer version could be released containing the  implemented deserializing support.

Then We could specify the 0.21.0 for that
