### ISSUE TITLE
How to qeury the mouse events?

### ISSUE THREAD

**Issue by JamRemco** [crossterm-rs/crossterm#593]
Hello world,

For the keyboard its easy 
`if event == Event::Key(KeyCode::Esc.into())`

but how does this work with the mouse?
i tried this `  if event == Event::Mouse(/MouseEventKind::Moved)`
and variations of this.

strangly, i couldnt find it in the docs either/

Regards,

Remco

**Comment by JamRemco** [comment]
to answer my own question......

`            let event = read()?;
            
            match event 
            {
              Event::Mouse(e) => match e.kind
              {
                MouseEventKind::Down(_)     => (),
                MouseEventKind::Drag(_)     => println!("Dragging on : {},{} ", e.column, e.row ),
                MouseEventKind::Moved       => println!("Moving on : {},{} ", e.column, e.row ),
                MouseEventKind::ScrollDown  => println!("Scrolling down .. "),
                MouseEventKind::ScrollUp    => println!("Scrolling up .. "),
                MouseEventKind::Up(_)       => println!("Click on : {:?},{} ",e.column, e.row),
              }
              _=>()
            }`

Just for reference 

Regards,

Remco

**Comment by stefnotch** [comment]
Apparently one first has to call `execute!(stdout, EnableMouseCapture)?;` before being able to capture mouse events. Leaving this here for any future readers

https://github.com/crossterm-rs/crossterm/blob/d638d15cd47cda7bc6baacea2ef81aebd5eb8e51/examples/event-read.rs#L70
