### ISSUE TITLE
Badly handles Cmd + Arrow in IntelliJ Terminal

### ISSUE THREAD

**Issue by ggoraa** [crossterm-rs/crossterm#597]
**Describe the bug**
Instead of displaying at least NONE + Left for Cmd + Left, it throws some gibberish

**To Reproduce**
1. Run this code:
```rust
loop {
        enable_raw_mode()?;
        let event = read()?;
        match event {
            Event::Resize(_, _) => {
                disable_raw_mode()?;
                continue;
            }
            Event::Key(KeyEvent { modifiers: modifier, code: key_code }) => {
                disable_raw_mode();
                println!("{:?} {:?}", modifier, key_code);
            }
            _ => {}
        }
}
```
2. Type for example Cmd + Arrow Right. It will be displayed as:
```
NONE Esc
NONE Char('[')
SHIFT Char('C')
```
in the command line, and:
```
NONE Esc
NONE Char('[')
SHIFT Char('D')
```
for Cmd + Arrow Left

**Expected behavior**
Show at least `NONE Left` or `CTRL Left` if pressed Cmd + Left, the same applies for right

**OS**
 - macOS

**Terminal/Console**
 - IntelliJ IDEA Terminal

Issue does not appear to work in iterm2. If I disable tab changing on Cmd + Arrow, and try to execute the thing, it will return me NONE + Left for Cmd + Left. Btw, I would be pleased to see an entry for Cmd key in `KeyModifiers` :D

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/crossterm-rs/crossterm/issues/685.
