### ISSUE TITLE
MoveToPreviousLine(0) and MoveToNextLine(0) move cursor by 1 line

### ISSUE THREAD

**Issue by and-nissa** [crossterm-rs/crossterm#599]
**Describe the bug**
hi all,
i noticed that using `crossterm::cursor::MoveToPreviousLine` and her sister command to move 0 lines moves the cursor by 1 line.

**To Reproduce**
Cargo.toml
```
...
[dependencies]
crossterm = "0.21.0"
```

main.rs
```
use std::io::stdout;

use crossterm::{cursor, execute};

fn main() {
    let stdout = stdout();
    let mut handle = stdout.lock();

    // MoveToPreviousLine(0)
    {
        let original_position = current_line();
        execute!(handle, cursor::MoveToPreviousLine(0)).unwrap();
        let new_position = current_line();

        print!("previous lines moved: {}", original_position - new_position);
    }

    // MoveToNextLine(0)
    {
        let original_position = current_line();
        execute!(handle, cursor::MoveToNextLine(0)).unwrap();
        let new_position = current_line();

        print!("next lines moved: {}", new_position - original_position);
    }
}

// position is a tuple: (column, row)
// this returns the row (at index 1)
fn current_line() -> u16 {
    cursor::position().unwrap().1
}
```

**Expected behavior**
shouldn't these *only* reset the column position? the documentation says that these commands "move the terminal cursor {up/down} the given number of lines...", but that given number is 0.

**OS**
x86_64-unknown-linux-gnu

**Terminal/Console**
xterm

```
$ xterm -version
XTerm(330)
```

**also**
this is my first opened issue, sorry if i messed anything up! i hope this is helpful in some way <3

**Comment by and-nissa** [comment]
it might also be worth mentioning that they behave as expected when the parameter is 1 (they move by 1 line)

**Comment by sigmaSd** [comment]
Hello, as you  can see here https://github.com/crossterm-rs/crossterm/blob/e1260446e94e9a8f7809fef61dc1369b6f8d6e12/src/cursor.rs#L86  crossterm is not doing anything special beides writing the correct eacape sequence, so if it moves with 0 then thats what ansi does.

The value 0 is underspecified in the spec https://en.m.wikipedia.org/wiki/ANSI_escape_code some sequences have a default value but the minimum value is not mentioned.

**Comment by and-nissa** [comment]
mkay~ so then it's a limitation (feature?) of ansi escape code standards.
in that case i think the docs should be a little clearer about that, especially since it explicitly says that it moves the cursor "the given number of lines".

**Comment by sigmaSd** [comment]
My understanding is since its not specified by the spec, terminals in thoery are free to implement it however they see fit, but I imagine in practice they try to maintain some unwritten conventions.

**Comment by TimonPost** [comment]
Move 0 times to the previous/next line seems should not do anything, like @sigmaSd says, maybe this is incorrectly implemented in the xterm since terminals are free to implement it as they wish, it should be validated in other terminals if this is a common problem, otherwise, I do think crossterm should either add a comment or check if the input count is 0.
