### ISSUE TITLE
"Pause" tui with crossterm to open dialoguer editor

### ISSUE THREAD

**Issue by on3iro** [crossterm-rs/crossterm#618]
Hey folks,

I am not quite sure, if this is the right place to ask a question like this, so feel free to point me into another direction ;)

I am building a small tui+crossterm application and have two threads - one for rendering and one for input polling.
However I want to spawn a  [dialoguer editor](https://docs.rs/dialoguer/0.9.0/dialoguer/struct.Editor.html) to allow the user to create some input. However only every other keypress is being registered by the editor. I assume that this is happening because crossterm captures these input events?

I tried to manually pause/resume the input polling thread by sending an `mpsc`-message on another channel, however this didn't work at all. I am also not quite sure which steps would be required, to make everything work - I assume I would also have to disable raw mode again?

Any advice on how I could achieve this, would be super helpful (I am pretty new to rust in general). Thanks in advance!

**Comment by sigmaSd** [comment]
Hi,

This should be possible by coordination between the two threads via channels, or using thread::park (on the input thread), if you can share your code I might be able to to take a look

You can checkout a very similar issue https://github.com/crossterm-rs/crossterm/issues/505

Also usually disabling raw mode is needed but not for the input but for the correct rendering of the application

**Comment by on3iro** [comment]
Awesome - thanks for the quick response @sigmaSd . I will have a look at the issue you mentioned and at `thread::park` as well and see where that takes me :)
I'll keep you posted on how it worked out. If I still hit a wall I will definitely get back to you offer of a small code review. I have not (yet) published the code on github ;)

**Comment by on3iro** [comment]
@sigmaSd I got it to work. I just realized that I used `rcv()` instead of `try_rcv()` on my woker-channel, which blocked the application 🙈. Thanks again for pointing me into the right direction 👍 (so my solution was to communication via channels as you suggested)

**Comment by pkulak** [comment]
Hey, hopefully I'm not abusing any good will here, but I was able to get this working perfectly by parking threads (thank you!), but when the child process terminates, I come back to an empty terminal (I actually see my compiler warnings from cargo run) that never renders again, despite the loop unparking fine and responding to input events. Is it possible I'm missing something I need to be doing with stdio or similar?
