### ISSUE TITLE
Is there a ClearType missing?

### ISSUE THREAD

**Issue by markus-bauer** [crossterm-rs/crossterm#624]
These are the supported clear types and their terminal escape sequences (for unix):

https://github.com/crossterm-rs/crossterm/blob/master/src/terminal.rs#L323 

```rust
impl Command for Clear {
    fn write_ansi(&self, f: &mut impl fmt::Write) -> fmt::Result {
        f.write_str(match self.0 {
            ClearType::All => csi!("2J"),
            ClearType::Purge => csi!("3J"),
            ClearType::FromCursorDown => csi!("J"),
            ClearType::FromCursorUp => csi!("1J"),
            ClearType::CurrentLine => csi!("2K"),
            ClearType::UntilNewLine => csi!("K"),
        })
    }
    ...
```
Searching for these, I found that there might be one missing.
(for example here: https://espterm.github.io/docs/VT100%20escape%20codes.html
or here: https://www2.ccs.neu.edu/research/gpc/VonaUtils/vona/terminal/vtansi.htm):

>Clear line from cursor right           ^[[K
Clear line from cursor right           ^[[0K
Clear line from cursor left            ^[[1K
Clear entire line                      ^[[2K
Clear screen from cursor down          ^[[J
Clear screen from cursor down          ^[[0J
Clear screen from cursor up            ^[[1J
Clear entire screen                    ^[[2J

Am I right, that *clear line from cursor left* (1K) is not implemented?

**Comment by TimonPost** [comment]
That's correct, currently not supported yet. And implementation would have to be done for `terminal/sys/windows.rs:69` as well, this is for compatibility with Windows 7/8 systems.

**Comment by markus-bauer** [comment]
Okay, thanks.
