### ISSUE TITLE
MoveToColumn(0) no longer works after version 0.23

### ISSUE THREAD

**Issue by chenxiaolong** [crossterm-rs/crossterm#632]
**Describe the bug**

After version 0.23, it seems that `MoveToColumn(0)` no longer has any effect. I did a git bisect between 0.22 and 0.23 and it seems the problem was introduced in commit 9a50fd2ce2701bb15f58722495024937143ad34d. I suspect it's due to this check:

https://github.com/crossterm-rs/crossterm/blob/9a50fd2ce2701bb15f58722495024937143ad34d/src/cursor.rs#L137-L139

**To Reproduce**

Small reproducer:

```
use std::io::{stderr, Write};

use crossterm::{
    cursor::MoveToColumn,
    queue,
    style::Print,
    Result,
};

// cargo run --example stderr
fn main() -> Result<()> {
    let stderr = &mut stderr();

    queue!(
        stderr,
        Print("hello"),
        MoveToColumn(0),
        Print("world"),
    )?;

    stderr.flush()?;

    Ok(())
}
```

On Windows and Linux, the output is:

```
helloworld
```

**Expected behavior**

Prior to version 0.23, the output was:

```
world
```

(`hello` being overwritten due to moving the cursor to the leftmost column)

**OS**

Windows 10 21H2; Fedora 35

**Terminal/Console**

Windows Terminal on Windows; Alacritty on Linux

**Comment by chenxiaolong** [comment]
Thanks, I saw that the documentation for `MoveTo()` used 0-indexed coordinates. I didn't realize `MoveToColumn()` would be 1-indexed.

**Comment by sidju** [comment]
It would be less unexpected if crossterm consistently used either 0- or 1-indexed cursor coordinates for all absolute movement, so either MoveTo or MoveToColumn/Row should follow the praxis of the other.
