### ISSUE TITLE
Terminal is not processing events

### ISSUE THREAD

**Issue by ivanceras** [crossterm-rs/crossterm#634]
**Describe the bug**
I have an TUI app that works perfectly find when using crossterm from version `0.16` to `0.18`, but breaks
in `0.19.0` to the latest `0.23.0`

Crossterm events such as Mouse clicks and Key events are processed correctly in `0.16` to `0.18.`
However, when I migrated the code to `0.23.0`, the events seemed to be not processed correctly, and I can all the event keycodes populating the command line after the app exited.
This is also the same behavior to `0.19.0` and in between versions up to `0.23.0`

**Expected behavior**
The mouse events and keyboard events should be processed correctly in the app in the same way I was using crossterm `0.16.0`, but upon migration to `0.23.0` it seems to be just building in the command line buffer after the app is exited.

**OS**
 - e.g. Linux(ubuntu 20)

**Terminal/Console**
 - The default terminal app in Ubuntu

**Comment by sigmaSd** [comment]
Can you share the code?

**Comment by ivanceras** [comment]
My bad, it turns out that I interchange the use of row and column for the x and y position, causing my calculation to the widget location to miss.
With that corrected, I noticed that the new version (0.23.0) is very slow compared to the old version 0.18.0.

A mouse clicking has a significant delay.
