### ISSUE TITLE
Is it possible to get a keyboard input on key down instead of key release?

### ISSUE THREAD

**Issue by Cl00e9ment** [crossterm-rs/crossterm#642]
The title is self explanatory. Here is an example program that let you type text (exit with `Ctrl+Q`):

```rust
use crossterm::{cursor, execute};
use crossterm::event::{read, Event, KeyCode, KeyEvent, KeyModifiers};
use crossterm::style::Print;
use crossterm::terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen};
use std::io::stdout;

fn main() {
    let mut stdout = stdout();
    enable_raw_mode().unwrap();

    execute!(stdout, EnterAlternateScreen, cursor::MoveTo(0, 0), Print("> ")).unwrap();

    loop {
        match read().unwrap() {
            // Ctrl+Q to exit
            Event::Key(KeyEvent {code: KeyCode::Char('q'), modifiers: KeyModifiers::CONTROL }) => {
                break;
            },
            // Write any character
            Event::Key(KeyEvent {code: KeyCode::Char(c), modifiers: KeyModifiers::NONE}) => {
                execute!(stdout, Print(c)).unwrap();
            },
            _ => (),
        }
    }

    execute!(stdout, LeaveAlternateScreen).unwrap();
    disable_raw_mode().unwrap();
}
```

Is it possible to get the character on key down instead of key release so it can behave like a true text input? This seams to be addressed in issue #75 but after reading the doc, I had not found how to do it.

Thanks!

**Comment by sharnoff** [comment]
AFAIK this is dependent on your terminal emulator. Crossterm gives the event once it receives the appropriate input, but whether that's on keydown or keyup is controlled by your terminal.

**Comment by Cl00e9ment** [comment]
> AFAIK this is dependent on your terminal emulator. Crossterm gives the event once it receives the appropriate input, but whether that's on keydown or keyup is controlled by your terminal.

I don't think so. Because in my (Manjaro) terminal emulator, vi, emacs, nano and even kiro which is Rust based (but use termion instead of crossterm) are writing the character on key down but no key release.

**Comment by sharnoff** [comment]
Oh interesting! Which terminal emulator are you using? I'll have a look to see if I can tell what's happening

**Comment by Cl00e9ment** [comment]
I'm using the GNOME terminal, version 3.42.2

**Comment by sharnoff** [comment]
@Cl00e9ment I've tried your code on i3 and Gnome (both Wayland and Xorg), both with gnome-terminal (3.42.2, pulled from arch repos) and kitty (0.24.4) and seem to be getting immediate printing of the character when I press down the key on my keyboard (tested by press + hold). FWIW, I've also seen the same results with the `event-read` example.

This was on the current master branch (72ce50ef)- if you're not using the latest commit, perhaps try pulling & see if your code works as intended? (I tested by adding your snippet as a file in the examples directory, and running `cargo run --example <filename>`)

Alternatively, perhaps I've misunderstood what the problem is? Could you elaborate on the precise behavior you're seeing?

**Comment by Cl00e9ment** [comment]
Wow, I can't reproduce the issue, even with my original setup. Since I opened the issue, I did nothing beside restarting my computer. That's really strange...

Also, now that I think about it, I'm not really sure if the behavior that I observed was in the GNOME terminal emulator or in my IDE terminal emulator (CLion), or in both.

I guess I can close the issue. Sorry for bothering you with that.

**Comment by Cl00e9ment** [comment]
OK, I know what I did wrong. Instead of passing `KeyModifiers::NONE` I passed a "wilcard" value. I corrected that but didn't realize that it was causing the key to be printed after release.
