### ISSUE TITLE
allow application to received args via piped stdin

### ISSUE THREAD

**Issue by coloradocolby** [crossterm-rs/crossterm#644]
**Is your feature request related to a problem? Please describe.**
caveat: I'm relatively new to rust, and by extension crossterm, so it's possible this feature already exists, however I haven't been able to find any examples in the documentation.

I'm working on a TUI application using [tui](https://crates.io/crates/tui) and crossterm under the hood. As part of my application, I'm hoping to allow for users to pipe in a particular parameter. An example would look like

`cat foo.txt | my_app`
or a slightly different example
`cat foo.txt | xargs my_app -p`

Each time I attempt to do this I hit the following error:
`Custom { kind: Other, error: "Failed to initialize input reader" }`

I believe this is happening because stdin is no longer a tty? I'm a little unsure on that.

Is what I'm trying to accomplish possible, or is this a limitation of crossterm? If it is (or is not) possible, would someone mind giving me a small primer on how/why? I'm super keen on understanding this problem space better. 

**Describe the solution you'd like**
All I want is to allow users to pipe in an argument via stdin to my application.

**Describe alternatives you've considered in any**
As stated above, I've tried using xargs in hopes that that might resolve the issue but i'm still not having success.

**Additional context**
Here is my main fn if that helps conceptualize 

```
fn main() -> Result<(), Box<dyn Error>> {


    // check for input on stdin here, if it exists, store it, otherwise continue


    let args = Args::parse();
    enable_raw_mode()?;

    let mut stdout = io::stdout();

    execute!(stdout, EnterAlternateScreen)?;

    let backend = CrosstermBackend::new(stdout);

    let mut terminal = Terminal::new(backend)?;

    let mut app = App::new(args);
    let result = run_app(&mut terminal, &mut app);

    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen,)?;
    terminal.show_cursor()?;

    if let Err(err) = result {
        println!("{:?}", err)
    }

    Ok(())
}
```

**Comment by sigmaSd** [comment]
Its a current limitation of crossterm https://github.com/crossterm-rs/crossterm/issues/396

**Comment by devdeadly** [comment]
> Its a current limitation of crossterm #396

Ah bummer. I read through that issue earlier and couldn't quite piece together if it was the same issue I was running into. I'm still curious as to the _why_, though. Was my assumption about stdin's tty being closed correct?

**Comment by sigmaSd** [comment]
What I remember is windows and linux works

only mac doesn't work and the issue is explained here https://github.com/crossterm-rs/crossterm/issues/500

**Comment by devdeadly** [comment]
big bummer :/ can confirm my code works on Linux
