### ISSUE TITLE
event module documentation dead link

### ISSUE THREAD

**Issue by SenojLuap** [crossterm-rs/crossterm#649]
**Describe the bug**
In the module documentation for crossterm::event, it makes the statement "Make sure to enable [raw mode](https://docs.rs/crossterm/0.23.2/crossterm/event/terminal/index.html#raw-mode) in order for keyboard events to work properly", however that pages does not exist

**To Reproduce**
n/a

**Expected behavior**
Unclear. If the page exists, but has been moved, the link should be updated to the new location. If the 'raw mode' is no longer relevant, then the comment should be removed.

**OS**
n/a

**Terminal/Console**
n/a

**Comment by SenojLuap** [comment]
Direct link to documentation page in question: https://docs.rs/crossterm/0.23.2/crossterm/event/index.html

**Comment by TimonPost** [comment]
I think its supposed to be this: https://docs.rs/crossterm/0.23.2/crossterm/terminal/index.html#raw-mode
