### ISSUE TITLE
How to handle CTRL-C?

### ISSUE THREAD

**Issue by peepopoggers** [crossterm-rs/crossterm#655]
I see lots of variants here: https://docs.rs/crossterm/latest/crossterm/event/enum.KeyCode.html

But I do not see CTRL+_ variant support anywhere. Where is this? Would appreciate help. Thanks!

**Comment by sigmaSd** [comment]
You can handle it with char + modifier:

```rust
KeyEvent {
  code: KeyCode::Char('c'),
  modifiers: KeyModifiers::CONTROL,
 } 
```

**Comment by peepopoggers** [comment]
thanks.

**Comment by peepopoggers** [comment]
For anyone curious, if matching `key.code` you can do this:

```rs
KeyCode::Char('c') => {
    if key.modifiers == KeyModifiers::CONTROL {
        // Quits parent loop
        return Ok(());
    }
}
```

**Comment by Android789515** [comment]
> For anyone curious, if matching `key.code` you can do this:
> 
> KeyCode::Char('c') => {
>     if key.modifiers == KeyModifiers::CONTROL {
>         // Quits parent loop
>         return Ok(());
>     }
> }

For clarification, key is of type `Event::Key` which has the modifiers property, and not `KeyCode` which is an enum and does not.
