### ISSUE TITLE
Example of alternate screen 

### ISSUE THREAD

**Issue by elferherrera** [crossterm-rs/crossterm#663]
Hi,

I'm trying to understand how to use alternative screen but I don't get it yet it. Is there any example out there that you could recommend?

**Comment by TimonPost** [comment]
This example uses alternate screen on stderr: https://github.com/crossterm-rs/crossterm/blob/master/examples/stderr.rs

**Comment by TimonPost** [comment]
Its simply:

execute!(stdout(), Show, EnterAlternateScreen)?;
execute!(stdout(), Show, LeaveAlternateScreen)?;

**Comment by elferherrera** [comment]
can it be lazily chained and then flushed?

**Comment by TimonPost** [comment]
Yea you can use queue with this command

**Comment by elferherrera** [comment]
Thanks. I will play with this for reedline
