### ISSUE TITLE
Mouse does not work on alacritty

### ISSUE THREAD

**Issue by cdecompilador** [crossterm-rs/crossterm#664]
**Describe the bug**
Mouse does not work on alacritty, it does not capture any event, tested with the latest commit of alacritty and a couple old versions.

**To Reproduce**
```rust
use std::io::stdout;

use crossterm::{
    QueueableCommand, 
    event::*,
    execute
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut stdout = stdout();
    
    execute!(stdout, EnableMouseCapture)?;
    
    loop {
        match read()? {
            Event::Key(KeyEvent {
                code: KeyCode::Char('c'),
                modifiers: KeyModifiers::CONTROL
            }) => break,
            Event::Mouse(event) => println!("{:?}", event),
            _ => {}
        }
    }
    
    Ok(())
}
```

**OS**
 - Windows

**Terminal/Console**
 - Alacritty

**Comment by TimonPost** [comment]
Let me have a look.

**Comment by TimonPost** [comment]
I just downloaded the latest Alacritty-v0.10.1-portable version on windows. When I run exact your example I just get mouse events. Can you revalidate with latest crossterm if this issue is still relevant?

**Comment by TimonPost** [comment]
I did just validate key events dont work. But that is different from what you report: Mouse events not working.

**Comment by cdecompilador** [comment]
After some time I've realised that is windows related, it depends if you use `OpenConsole` or `conhost` maybe a workaraound to make it work in both would be a temporal solution.

I'll close this as that another type of issue
