### ISSUE TITLE
`Shift`/`Ctrl` + `Enter` returns `modifiers::NONE`

### ISSUE THREAD

**Issue by Araxeus** [crossterm-rs/crossterm#669]
**Describe the bug**
<kbd>Ctrl</kbd> + <kbd>Enter</kbd> = `modifiers::NONE`
<kbd>Shift</kbd> + <kbd>Enter</kbd> = `modifiers::NONE`

<kbd>Alt</kbd> + <kbd>Enter</kbd> =  `modifiers::ALT`

**To Reproduce**
```rust
use crossterm::{event::read, terminal};

fn main() {
	terminal::enable_raw_mode();
	let res = read().unwrap();
	terminal::disable_rawmode();
	println!("{:#?}", res);
}
```

**OS**
 - Ubuntu 21.10

**Terminal/Console**
 - gnome-terminal

I couldn't test on Mac, but on Windows - all modifiers are returned just fine

**Comment by doinkythederp** [comment]
Can reproduce on macOS using a few different terminals

Code I used:
```rust
use crossterm::{event::read, terminal};

fn main() -> std::io::Result<()> {
    terminal::enable_raw_mode()?;
    let res = read()?;
    terminal::disable_raw_mode()?;
    println!("{:#?}", res);
    Ok(())
}
```

- iTerm2, Terminal.app
  - <kbd>Ctrl</kbd> + <kbd>Enter</kbd> = `NONE`
  - <kbd>Shift</kbd> + <kbd>Enter</kbd> = `NONE`
  - <kbd>Alt</kbd> + <kbd>Enter</kbd> = `NONE`
- VSCode Integrated Terminal
  - <kbd>Ctrl</kbd> + <kbd>Enter</kbd> = `NONE`
  - <kbd>Shift</kbd> + <kbd>Enter</kbd> = `NONE`
  - <kbd>Alt</kbd> + <kbd>Enter</kbd> = `ALT`

**Comment by TimonPost** [comment]
Thanks for reporting the missing keys, those key combinations are likely not implemented yet. I'll leave this issue open such that people can add support for the keys.

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/crossterm-rs/crossterm/issues/685.
