### ISSUE TITLE
Incorrect mouse buttons in events.

### ISSUE THREAD

**Issue by chyvonomys** [crossterm-rs/crossterm#670]
**Describe the bug**
EventStream returns incorrect button in MouseEventKind::Up
I use raw mode and MouseCaptureEnabled.

Middle and Right are not working properly:
 - Press middle mouse button, release middle mouse button. I receive Down(Middle), Up(**Left**)
 - Press right mouse button, release right mouse button. I receive Down(Right), Up(**Left**)
 
Left button works fine.

Stacking more that one button is not working either, notice even Down is not correct:
 - Press Left, press Right, release Left, release Right. I receive Down(Left), Down(Right), Up(**Right**), Up(**Left**)
 - Pres Left, press Right, release Right, release Left. I receive Down(Left), Down(Right), Up(**Left**), Up(Left)
 - Press Right, press Left, release Right, release Left. I receive Down(Right), Down(**Right**), Up(**Left**), Up(Left)
 - Press Right, press Left, release Left, release Right. I receive Down(Right), Down(**Right**), Up(**Right**), Up(**Left**)

Also, double clicking skips second "Down(Left)"
- Press Left, release Left, press Left, release Left. I receive Down(Left), Up(Left), Up(Left)

Observation:  if between clicks I move mouse then it doesn't drop second "Down(Left)"

**To Reproduce**
See above

**Expected behavior**
Correct mouse up buttons in event.

**OS**
 - Windows

**Terminal/Console**
 - both conhost/WindowsTerminal

**Comment by TimonPost** [comment]
> Press Left, press Right, release Left, release Right.
![image](https://user-images.githubusercontent.com/19969910/177010934-5f3f4042-8b05-4ad9-a692-939969ceb5d6.png)

> Pres Left, press Right, release Right, release Left. I
![image](https://user-images.githubusercontent.com/19969910/177011071-f62aa781-dd24-46ca-ae36-b5170926a541.png)

> Press Right, press Left, release Right, release Left. 
![image](https://user-images.githubusercontent.com/19969910/177011090-3aca9006-b44f-4d20-980f-7f03924ab7ae.png)

> Press Right, press Left, release Left, release Right

![image](https://user-images.githubusercontent.com/19969910/177011107-44fdbe04-eea7-4c55-8fb3-9f0faa86fe7a.png)

> Press Left, release Left, press Left, release Left. 
![image](https://user-images.githubusercontent.com/19969910/177011131-a9ff374c-05fa-4262-b25b-b829fe8f416c.png)

When I run this code with windows terminal with powershell window opened in it (what terminal do you use within windows terminal?) I seem to get only good results. 

As for the double click, I suspect it might be normal for there to be two ups. That way one can deduce it's with a double click. 


I will test conhost now.

**Comment by TimonPost** [comment]
It might actually be the case: https://github.com/crossterm-rs/crossterm/commit/d48ae42824b7061c435e78f147356be47784e56b that this PR fixed it?

**Comment by TimonPost** [comment]
Yes, I think that commit solves it. Closing this issue now.

**Comment by chyvonomys** [comment]
I upgraded to 0.24. and it works as expected now. Thanks!
Double clicks still send 1 down and 2 ups.. Yes, I use async `EventStream`.
