### ISSUE TITLE
Setsize doesnt work

### ISSUE THREAD

**Issue by vsjoqvist** [crossterm-rs/crossterm#678]
**Describe the bug**
crossterm::terminal::SetSize;

**To Reproduce**
Run 
println!("{:?}", size()?);
execute!(stdout(), SetSize(100, 100))?;
println!("{:?}", size()?);

**Expected behavior**
The values wont change

**OS**
Arch linux (kernel 5.17.9)

**Terminal/Console**
Konsole and Kitty

**Comment by TimonPost** [comment]
It is likely working but your terminal is not resized rather its the terminal buffer.

**Comment by TimonPost** [comment]
Otherwise your terminal does not support it.

**Comment by TimonPost** [comment]
This is the definition crossterm maintains. Likely we might need to add a comment that clarifies the difference. 

```
ESC [ 8 ; Ph ; Pw t             Resize the window to ‘Ph’ lines and
                                ‘Pw’ columns (SunView special)
```
https://www.gnu.org/software/screen/manual/html_node/Control-Sequences.html

**Comment by TimonPost** [comment]
Clarified by: 645685641ac98d3af4c7be9ff44b9b5a00da6b2e
