### ISSUE TITLE
Read key event without waiting for enter

### ISSUE THREAD

**Issue by igoracmelo** [crossterm-rs/crossterm#682]
**Is your feature request related to a problem? Please describe.**
The input is only read when I press enter.
I would like to read keydown.
![image](https://user-images.githubusercontent.com/85039990/176045300-d0842e4e-ffbc-42a5-b783-43b007ce56a3.png)

**Describe the solution you'd like**
Being able to read the event in the moment the key is pressed.

**Comment by sigmaSd** [comment]
See https://github.com/crossterm-rs/crossterm/issues/637#issuecomment-1059710880

**Comment by igoracmelo** [comment]
@sigmaSd Thank you!

For people that my search for this: https://docs.rs/crossterm/latest/crossterm/terminal/index.html#raw-mode
