### ISSUE TITLE
no mouse modifiers using konsole

### ISSUE THREAD

**Issue by deltanedas** [crossterm-rs/crossterm#708]
**Describe the bug**
Mouse up/down/move events never have `KeyModifier`s applied.
Tested with ctrl and alt, shift+click is used directly by konsole so that probably shouldn't be known.

**To Reproduce**
1. compile this using latest crossterm on crates.io:
```rs
use std::io::stdout;
use crossterm::*;
fn main() -> Result<()> {
	terminal::enable_raw_mode()?;
	execute!(stdout(), event::EnableMouseCapture)?;
	println!("Capturing events, press any key to exit\r");
	loop {
		let event = event::read()?;
		println!("Event: {event:?}\r");
		if let event::Event::Key(_) = event {
			break;
		}
	}
	terminal::disable_raw_mode()?;
	execute!(stdout(), event::DisableMouseCapture)
}
```

2. run it
3. hold ctrl and click, modifiers are still `NONE`!

**Expected behavior**
hold control to get a modifier

**OS**
linux 5.18.0-4-amd64

**Terminal/Console**
Konsole X11 22.04.1

**Comment by TimonPost** [comment]
I moved your report over to: https://github.com/crossterm-rs/crossterm/issues/685.
