### ISSUE TITLE
Newline starts below end of last line, instead of beginning of newline.

### ISSUE THREAD

**Issue by JustASpeedrunner** [crossterm-rs/crossterm#709]
**Describe the bug**
Run any code that has text starting on a newline, it _does_ go to a newline, but it is staggered by however far the line above it went.

**To Reproduce**
1. Run the below code (within proper context)
 ```
execute!(
        stdout(),
        SetForegroundColor(Color::White),
        SetBackgroundColor(Color::Black),
        Print(r#"Some text here
Then the newline.
And another."#),
        ResetColor).ok();

or

execute!(
        stdout(),
        SetForegroundColor(Color::White),
        SetBackgroundColor(Color::Black),
        Print("Some text here\nThen the newline.\nAnd another."),
        ResetColor).ok();
```
2. See error: 
![image](https://user-images.githubusercontent.com/30637257/188543725-7ceae2c5-beab-4f62-b46d-77d89433e0ce.png)

**Expected behavior**
Newline would begin at the first character in the line

**OS**
-Pop!_OS 22.04

**Terminal/Console**
 - GNOME Terminal, default with Pop!_OS

**Comment by sigmaSd** [comment]
That's expected, you have to enable raw mode to get the behavior you're looking for.

**Comment by TimonPost** [comment]
Yes or use the move cursor commands to get proper behaviorf

**Comment by sigmaSd** [comment]
Actually my last comment is wrong, this **only** happens in raw mode. This is expected, as Timon said you should use move cursor commands after printing, I personally sometimes use Print(.. + "\r\n") but I'm not sure if that always works.

**Comment by JustASpeedrunner** [comment]
I see, thank you both! I figured it was intentional but I guess I missed it

**Comment by TommyDew42** [comment]
@TimonPost Thanks for the guidance here! I'm interested in the internal of raw mode. Do you mind explaining a bit why there's extra spaces in new lines under raw mode?
