### ISSUE TITLE
Add feature to save and restore the terminal state (like tcgetattr and tcsetattr)

### ISSUE THREAD

**Issue by Mulling** [crossterm-rs/crossterm#710]
There isn't (and I did look for it, but please, correct me if I'm wrong) a feature to save and restore the "state" of the terminal like the good old `termios.h`, where you can easily save and restore the terminal sate with:

```c
int tcgetattr(int fd, struct termios *termios_p);
int tcsetattr(int fd, int optional_actions, const  struct termios *termios_p);
```

This is useful because programs that change the terminal behavior **must** restore the said terminal behavior on exit, and quite a few don't do that. And it is quite hard do this manually, unwinding on all the errors.

One solution that comes to mind would be something like:
```rust
let term_state = crossterm::terminal::get_terminal_state()?;
// [...]
// something went wrong, restore the terminal state before exiting.
crossterm::terminal::set_terminal_state(term_state)?;
```
I'm kinda new to using crossterm and don't have a lot of time, I'll see if I can come up with something tho.

**Comment by sigmaSd** [comment]
I think it be weird to expose termios in the api.

Can you explain your use case more, adding this api won't change the fact that you still have to clean up manually and catch panics.

And it's already just a couple of lines of code, something like

```
impl Drop for App {
 fn drop() {
     disable raw mode
     show cursor
     etc
}
}
```

**Comment by TimonPost** [comment]
In the past crossterm was used to support this. However, we moved on from a state-based api accessible from a single struct `Terminal` instance to more of a stateless approach. We internally do keep track of the original state but there is no good way for us to revert this state on panics. This is something you have to implement in user space im afraid

**Comment by Mulling** [comment]
Ok, so I misinterpreted some things, but `disable_raw_mode` does restore the previous terminal state. If you do `stty -echo` then run `enable_raw_mode(); disable_raw_mode()` the terminal state is the same as before.

Thanks!
