### ISSUE TITLE
Allow checking for keyboard enhancement support

### ISSUE THREAD

**Issue by pianohacker** [crossterm-rs/crossterm#717]
**Is your feature request related to a problem? Please describe.**
The new keyboard enhancement feature is supported by a small (if growing) subset of terminals. It would be nice to know if the current terminal supports the protocol. This allows adjusting expected keyboard inputs, changing shortcuts,  etc.

**Describe the solution you'd like**
The [suggested way](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#detection-of-support-for-this-protocol) to check for support is to:
- send a query escape sequence for the current keyboard enhancement status
- send a query for the primary device attributes
- check if we got two answers, or just one

I'm not immediately sure a) how to reliably do this and b) how we could provide a helper in crossterm itself. Desired workflow would just be something like:

```rust
if crossterm::event::detect_keyboard_enhancement_support(&mut stdout)? {
...
```

**Describe alternatives you've considered if any**
I don't _think_ there's any other way to detect support. Enabling keyboard enhancement then checking the form of incoming events is possible, but that seems messy and unreliable.

**Comment by pianohacker** [comment]
@TimonPost , would love your thoughts here.

**Comment by TimonPost** [comment]
Would be nice to have this support. I also am not aware with how reliable this is, but we can expose the function at least and have users be able to call it. At least not directly depending crossterm on this logic.
