### ISSUE TITLE
Ctrl+shift+Letters only gives the modifier ctrl

### ISSUE THREAD

**Issue by Dimev** [crossterm-rs/crossterm#719]
**Describe the bug**
When trying to enter anything with the ctrl+shift+letter combination, it only registers ctrl as the modifier. All letters are also lowercase.
Arrow keys seem to work properly here.

**To Reproduce**
check for key events and print their modifiers, as described in #685.

**Expected behavior**
ctrl+shift+capital letter should get the proper modifiers when pressed.

**OS**
Linux.

**Terminal/Console**
 Alacritty, Kitty and tty.

**Comment by TimonPost** [comment]
This is a pretty advanced combination and is likely not to work on unix based terminals. I moved your report over to: https://github.com/crossterm-rs/crossterm/issues/685.

**Comment by Dimev** [comment]
alright, thanks!
