### ISSUE TITLE
Guard style API for raw mode

### ISSUE THREAD

**Issue by pacak** [crossterm-rs/crossterm#720]
**Is your feature request related to a problem? Please describe.**

Currently you enable/disable raw mode using `enable_raw_mode()`/`disable_raw_mode()` commands - this results in a messed up terminal if your program crashes.

**Describe the solution you'd like**
```rust
struct RawModeGuard;
impl RawModeGuard {
    pub fn new() -> std::io::Result<Self> {
        crossterm::terminal::enable_raw_mode()?;
        Ok(RawModeGuard)
    }
}

impl Drop for RawModeGuard {
    fn drop(&mut self) {
        crossterm::terminal::disable_raw_mode().unwrap();
    }
}
   // usage example
fn main() -> Result<()> {
    ...
    // automagically restores terminal mode when app exits or crashes
    let _guard = RawModeGuard::new()?;
    ...
}
```

**Describe alternatives you've considered in any**
Having them defined locally and copy-paste from project to project...

**Comment by sigmaSd** [comment]
It used to be the case but it was removed, the current design of crossterm is to not keep state.

I think it's just a couple of lines so it doesn't seem like a big deal.

**Comment by pacak** [comment]
Can you use raw mode (in a program that can crash) without writing something like this by hands?

**Comment by TimonPost** [comment]
Thanks for filing the issue and thinking about how to improve crossterm. @sigmaSd is right, this was how it worked in the past, but since then we've moved to a mostly stateless lib as it introduced challenges and unpredictability in the API.  One can build  a custom library ontop of crossterm and publish it.
