### ISSUE TITLE
ctrl + backspace doesnt work? or its not supported, cuz linux terminal stuff?

### ISSUE THREAD

**Issue by alexzanderr** [crossterm-rs/crossterm#723]
hello.

love your crate.

```rust
                    KeyEvent {
                        code: KeyCode::Backspace,
                        modifiers: event::KeyModifiers::CONTROL,
                        ..
                    } => {
                        // do something with the control backspace
                    },
```
i've seen that this combination doesnt work. should this work? is it supposed to be working? its a bug?

but this combination is working:
```rust
                    KeyEvent {
                        code: KeyCode::Backspace,
                        modifiers: event::KeyModifiers::ALT,
                        ..
                    } => {
                        // do something with the control backspace
                    },
```
what is happening? what am i missing?

from all command-line apps  that i've interacted with (the rust ones, im talking about) none of them was able to make ctrl+backspace to work, only alt+backspace was working by default. 
is this issue the reason for these apps? 

im using `crossterm = "0.25.0"`

thanks in advance.

**Comment by TimonPost** [comment]
Thanks for filing issue, this missing combination is already reported here: https://github.com/crossterm-rs/crossterm/issues/685. Either not implemented or can not be handled. Closing this issue in favour of that tracking issue.

**Comment by alexzanderr** [comment]
sure, thanks for your response

**Comment by alexzanderr** [comment]
actually found out that `ctrl+backspace` works, but its not what was expected.
```rust
                    KeyEvent {
                        code: KeyCode::Char('h'),
                        modifiers: event::KeyModifiers::CONTROL,
                        ..
                    } => {
                        user_input.clear();
                        self.term
                            .print("you pressed control backspace", 20, 0)?
                            .refresh()?;
                    },
```
you know that in linux terminals actually ctrl+backspace is ctrl+h.
