### ISSUE TITLE
I wish it to be a global detection, no depend on terminal input

### ISSUE THREAD

**Issue by swithun-liu** [crossterm-rs/crossterm#724]
**Is your feature request related to a problem? Please describe.**

I tried crossterm,

but those bytes are only passed from the terminal to the shell's stdin when the user presses a new line.

I wish it to be a global detection

**Describe the solution you'd like**

**Describe alternatives you've considered in any**

**Additional context**
Anything else?

**Comment by sigmaSd** [comment]
It's not clear what you're asking, but if you mean the user have to use enter before you get the keys on crossterm read, you have to enable raw mode to make the input be passed directly

**Comment by swithun-liu** [comment]
> It's not clear what you're asking, but if you mean the user have to use enter before you get the keys on crossterm read, you have to enable raw mode to make the input be passed directly

the thing that I want implement is, such as I press `cmd + c` (`ctr + c` on windows) 3 times on a text in chrome webpage, then the process will detect that and do something

**Comment by sigmaSd** [comment]
That's out of scope for crossterm, I'm sure there are crates that can do this for windows I guess you will need to search crates.io

**Comment by swithun-liu** [comment]
> That's out of scope for crossterm, I'm sure there are crates that can do this for windows I guess you will need to search crates.io

I see, thx
