### ISSUE TITLE
Modifiers keys are not detected for KeyCode::Enter

### ISSUE THREAD

**Issue by aaron404** [crossterm-rs/crossterm#773]
**Describe the bug**

**To Reproduce**
1. Poll for events
2. Press a letter key (such as A, B, etc) while holding shift or control, these modifiers will be reported correctly
3. Repeat the test but by pressing Enter while holding shift or control. No modifier will be reported.

**Expected behavior**
Modifiers (ctrl, shift, alt, etc) should be reported when Enter is pressed

**OS**
Ubuntu via Windows WSL

**Terminal/Console**
Windows terminal

**Comment by dob9601** [comment]
Can confirm that this affects me too

**Comment by TimonPost** [comment]
Please post your issue here: https://github.com/crossterm-rs/crossterm/issues/685. It also seems like the modifiers + ENTER combo was already reported, additional information would be the systems that those are not supported on. Thanks.
