### ISSUE TITLE
Bracketed Paste does not preserve newline characters

### ISSUE THREAD

**Issue by technologicalMayhem** [crossterm-rs/crossterm#780]
**Describe the bug**
When using bracketed paste, pasting text that contains newline characters, the text is stripped of the newline characters. As far as I can tell, bracketed paste should preserve newlines.

**To Reproduce**
1. Enable bracketed paste
2. Run the application and paste text containing newlines
3. Checking the pasted text for newline characters returns false

**Expected behavior**
The pasted text should preserve the newline characters.

**OS**
 - Arch Linux

**Terminal/Console**
 - Yakuake
 - Konsole

**Comment by sigmaSd** [comment]
works for me (linux, wezterm), also helix been using it for a while and it works there as well (doesn't work at all on windows though)

to test git clone this repo, cargo r --example event-read, copy some multine code, paste it and it have `\n` 
![image](https://user-images.githubusercontent.com/22427111/231770877-cd894b45-c495-44fb-893a-60b3f51dc9f0.png)
