### ISSUE TITLE
Document the feature `use-dev-tty` on `crossterm::event::{poll, read}`

### ISSUE THREAD

**Issue by sigoden** [crossterm-rs/crossterm#849]
**Is your feature request related to a problem? Please describe.**

If you use `crossterm::event::poll`/`crossterm::event::read`, and if your CLI supports reading from stdin, then an error will occur on macOS.

sigoden/aichat#257  helix-editor/helix#5468.

This is a trap.

**Describe the solution you'd like**

Add a document on `crossterm::event::poll`/`crossterm::event::read` to warn developers about the problem and the solution.

**Comment by texastoland** [comment]
Your issue helped me fix a bug! But I checked the commit history and couldn't find where it's documented?
