### ISSUE TITLE
Build error with use-dev-tty

### ISSUE THREAD

**Issue by gwenn** [crossterm-rs/crossterm#886]
**Describe the bug**
Build fails with `use-dev-tty` feature

**To Reproduce**

```sh
% cargo check --no-default-features --features "use-dev-tty events"
...
error[E0061]: this method takes 1 argument but 2 arguments were supplied
  --> src/event/source/unix/tty.rs:83:18
   |
83 |         match fd.read(buf, buf.len()) {
   |                  ^^^^    -----------
   |                          | |
   |                          | unexpected argument of type `usize`
   |                          help: remove the extra argument
   |
note: method defined here
  --> src/terminal/sys/file_descriptor.rs:32:12
   |
32 |     pub fn read(&self, buffer: &mut [u8]) -> io::Result<usize> {
   |            ^^^^        -----------------
```

It seems to be related to #821

**Expected behavior**
The build should succeed.
And ideally, `use-dev-tty` should imply `events` but without `mio` dependencies.

**OS**
 - MacOs

**Comment by joshka** [comment]
Fixed in https://github.com/crossterm-rs/crossterm/pull/888

**Comment by gwenn** [comment]
Only partially fixed:
> And ideally, use-dev-tty should imply events but without mio dependencies.

**Comment by joshka** [comment]
> Only partially fixed:
> 
> > And ideally, use-dev-tty should imply events but without mio dependencies.

Can you expand on this?

**Comment by gwenn** [comment]
* `use-dev-tty` is useless without `events`
* but `events` implies `mio` while `mio` dependencies are useless with `use-dev-tty`

**Comment by joshka** [comment]
Got it - makes sense.
