### ISSUE TITLE
Pipe mode support

### ISSUE THREAD

**Issue by sshelll** [crossterm-rs/crossterm#939]
**Describe the bug**
Not able to read key event through pipe on Mac OS.

**To Reproduce**
run this code:
```rust
fn main() {
    use crossterm::{event, terminal};
    terminal::enable_raw_mode().unwrap();
    let _evt = event::read().unwrap();
    terminal::disable_raw_mode().unwrap();
}
```
with `./main` is ok.  
with `echo 1 | main` will cause panic with this info: 
```
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to initialize input reader" }
```

**Expected behavior**
Be able to read events through pipe.

**OS**
 - MacOS

**Terminal/Console**
 - Alacritty with Tmux

**Comment by sshelll** [comment]
Actually, `crossterm::cursor::position()` is also not working on MacOs -- It'll cause block.
So in my project, I replace this function with my own:
```rust
fn get_cursor_position() -> io::Result<(u16, u16)> {
    use std::fs::OpenOptions;
    use std::io::{self, Read, Write};
    // open tty
    let mut tty = OpenOptions::new().read(true).write(true).open("/dev/tty")?;

    // ask for cursor position
    write!(tty, "\x1b[6n")?;
    tty.flush()?;

    // read resp
    // resp fmt: \x1b[{row};{col}R
    let mut response = String::new();
    let mut buffer = [0; 1];
    while tty.read(&mut buffer)? == 1 {
        response.push(buffer[0] as char);
        if buffer[0] == b'R' {
            break;
        }
    }

    if let Some(caps) = response
        .strip_prefix("\x1b[")
        .and_then(|s| s.strip_suffix("R"))
    {
        let mut parts = caps.split(';');
        if let (Some(row), Some(col)) = (parts.next(), parts.next()) {
            let row = row.parse().unwrap_or(0);
            let col = col.parse().unwrap_or(0);
            return Ok((row, col));
        }
    }
    Err(io::Error::new(
        io::ErrorKind::Other,
        "Failed to parse cursor position",
    ))
}
```
However, refactoring and implementing those codes of reading events would be much more complicated in my project.  
So I opened this issue...🙏

**Comment by joshka** [comment]
Take a look at https://github.com/cosmikwolf/piped_cli_interactive for some ideas (via https://github.com/crossterm-rs/crossterm/pull/407)

**Comment by sshelll** [comment]
> Take a look at https://github.com/cosmikwolf/piped_cli_interactive for some ideas (via #407)

Thanks a lot, there're no more errors after adding the feature `use-dev-tty`.

Ps: `crossterm = { version = "0.28", features = ["use-dev-tty"] }`
