### ISSUE TITLE
Key release event seems not be fired on Linux

### ISSUE THREAD

**Issue by starccy** [crossterm-rs/crossterm#950]
**Describe the bug**
I'm trying to get the pressed and released events of a keyboard key. They both work on Windows, but I am unable to get released events on Linux.

**To Reproduce**
Here is a minimal demo based on the example code:
```rust
use std::io;

use crossterm::terminal::{disable_raw_mode, enable_raw_mode};
use crossterm::event::{read, Event, KeyCode, KeyEventKind};

fn main() -> io::Result<()> {
    enable_raw_mode()?;
    if let Err(e) = print_events() {
        eprintln!("Error: {:?}\r", e);
    }
    disable_raw_mode()?;

    Ok(())
}

fn print_events() -> io::Result<()> {
    loop {
        let event = read()?;
        match event {
            Event::Key(event)=> {
                if event.kind == KeyEventKind::Press {
                    println!("Key pressed: {}\r", event.code);
                    if event.code == KeyCode::Esc {
                        break;
                    }
                } else if event.kind == KeyEventKind::Release {
                    println!("Key pressed: {}\r", event.code);
                }
            }
            _ => {}
        }
    }
    Ok(())
}

```

**Expected behavior**
the `Key pressed` and the `Key pressed` logs should be both present when pressing and releasing a key.

But only the `Key pressed` log is printed.

**OS**

Kali Linux, with kernel version 6.10.11

**Terminal/Console**
 - Gnome Terminal
 - tty

**Comment by joshka** [comment]
There are docs for when kind is set on the key event https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html

**Comment by starccy** [comment]
Oh sorry I missed that.

**Comment by joshka** [comment]
Perhaps the docs should also be on the enum.
