### ISSUE TITLE
macOS selection box is wrong intented 

### ISSUE THREAD

**Issue by KuramaSyu** [crossterm-rs/crossterm#961]
I have a small CLI tool, which does everything correctly on macos except for the weird increasing intent, like on the screenshot. I tested a bit - it's the raw mode which causes issues
![image](https://github.com/user-attachments/assets/9cb1d6d5-01b3-48fd-8527-8eaee0acd459)

If you need more information:
https://github.com/KuramaSyu/acnh-backup/blob/6164d117bd63a9323923af0c55411d721987c534/src/main.rs#L19-L49
this is the source code. It's 250 lines - so not big at all. The marked 30 lines should already contain everything

**To Reproduce**
1. enter raw mode: `enable_raw_mode().expect("Failed to enable raw mode");`
2. make a selection menu:
```rs
let selection = Select::with_theme(&ColorfulTheme::default())
    .with_prompt("What would you like to do?")
    .item("Backup")
    .item("Restore")
    .item("Exit")
    .interact_opt()
    .expect("Failed to get user selection");
```
3. see, that it's buggy. I tested it in iterm2 and in the interated VSC terminal.

**Expected behavior**
A non intented selection menu

**OS**
macOS

**Terminal/Console**
 - iterm2, VSC integrated terminal - only on macos

**Comment by joshka** [comment]
Raw mode turns off processing newlines. This is expected behavior.
See https://docs.rs/crossterm/latest/crossterm/terminal/index.html#raw-mode
